### ISSUE TITLE
[selective_average] selectively average two anemometers at the same level

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#116]
Use code that Andy developed. This can be taken from an old stale branch. https://github.com/brightwind-dev/brightwind/tree/selective_averaging

**Comment by stephenholleran** [comment]
@Inder95 you worked on the old branch linked above. If you have made any developments to it and haven't pushed them since can you do so and I'll work on it tomorrow? Cheers.

**Comment by Inder95** [comment]
> @Inder95 you worked on the old branch linked above. If you have made any developments to it and haven't pushed them since can you do so and I'll work on it tomorrow? Cheers.

That is it no more change from my side.
