### ISSUE TITLE
[Tutorial] Useful Stats 

### ISSUE THREAD

**Issue by ShaneBrightWind** [brightwind-dev/brightwind#134]
I am already working on this and will have it done soon.

**Comment by stephenholleran** [comment]
@ShaneBrightWind  you accidentally created a branch off the shear branch and so have included some of those commits. Create a new branch off of master and paste in this .ipynb file again and push.

**Comment by ShaneBrightWind** [comment]
@stephenholleran This has been amended now and ready for you to merge

**Comment by ShaneBrightWind** [comment]
I created a new branch for this by the way called iss134_useful_stats_tut
