### ISSUE TITLE
[Tutorial] How to calculate shear

### ISSUE THREAD

**Issue by ShaneBrightWind** [brightwind-dev/brightwind#139]
This file should be called:

how_to_calculate_shear

it should look at the functions mentioned in the tutorial landing page. i.e. 

In this tutorial, you will learn how to calculate the shear in a variety of different ways and then scale it to hub height. The `Shear.power_law()` function is used to calculate the shear using the power law method. The `Shear.by_sector()` calculates the shear using the power law method by direction sector. The `Shear.apply()` function shows you how to apply your preferred shear method to the data. The `Shear.scale()` function scales the data by a fixed shear value to a specific height. The `Shear.twelve_by_24()` function plots a nice heat map showing the 12 month by 24 hour matrix of shear to see how shear varies diurnally throughout the year.

**Comment by lucunnin** [comment]
I have pushed this tutorial with the updated shear code in branch iss55_shear as the tutorial will not run with the current code.

**Comment by lucunnin** [comment]
@ShaneBrightWind 
Just FYI the description of how_to_calculate_shear on the tutorials landing page will have to be updated to align with the new naming conventions of the shear functions.
