### ISSUE TITLE
[monthly_means] modify plot when monthly coverage is returned

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#15]
When 'return_coverage=True' the plot should be modified to include bars indicating the monthly coverage. e.g. 
![image](https://user-images.githubusercontent.com/25622575/51108482-4c377600-17ea-11e9-9a5d-a0a15e5d015c.png)

This will obviously get very cluttered when multiple wind speeds are sent but that is up to the user to minimise what to send.

Try and match the colours in the example for the first wind speed column.

**Comment by Inder95** [comment]
![image](https://user-images.githubusercontent.com/23189856/56520314-094d1300-653c-11e9-9363-ec620445d8a1.png)

**Comment by Inder95** [comment]
![image](https://user-images.githubusercontent.com/23189856/56659343-c488bf80-6694-11e9-8cf5-16c82cd7cda1.png)
![image](https://user-images.githubusercontent.com/23189856/56659372-d79b8f80-6694-11e9-85ac-6b7242c23d45.png)
![image](https://user-images.githubusercontent.com/23189856/56659399-e7b36f00-6694-11e9-948c-208a3aa0d936.png)
![image](https://user-images.githubusercontent.com/23189856/56659418-f4d05e00-6694-11e9-9a05-3798427869fe.png)

**Comment by Inder95** [comment]
@stephenholleran your suggestions in GH-41  implemented here.

**Comment by stephenholleran** [comment]
Great.

Last thing. Add in these 2 lines to make it look like below. If that works then feel free to merge the branch.
```
ax2.yaxis.grid(True)
ax2.set_axisbelow(True)
```

![image](https://user-images.githubusercontent.com/25622575/56663245-8cd24580-669d-11e9-9345-6eeb23c509a3.png)

**Comment by Inder95** [comment]
![image](https://user-images.githubusercontent.com/23189856/56673919-09baea80-66b1-11e9-955e-1cd3683e71f2.png)
