### ISSUE TITLE
Shane pointed a few issues with tutorials, pasting them here from Slack

### ISSUE THREAD

**Issue by Inder95** [brightwind-dev/brightwind#153]
For tutorial 8, look to remove the link at the bottom of the page to the notebook for downloading
For the main tutorial landing page, for Tutorial 11, how to calculate shear, the function Shear.apply() should be updated to the name of what it is now. Ask Luke about this.

For plotting and understanding turbulence, the main tutorial landing page references a funciton TI.by_12x24() however this did not exist in the library i was working off, so i have used the function TI.twelve_by_24(), So if this has been renamed in library, then the tutorial will have to be updated appropriately

**Comment by stephenholleran** [comment]
- [ ] tutorial on exporting title isn't rendering
