### ISSUE TITLE
[dist_by_dir_sector] rename and fix

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#169]
- [x] The `distribution_by_dir_sector` should be renamed `dist_by_dir_sector` to be consistent with the other distribution function.

- [x] When I run `bw.distribution_by_dir_sector(data.Spd80mN, data.Dir78mS, aggregation_method='mean')` there are no axis labels to tell me the wind speed in each sector.
![image](https://user-images.githubusercontent.com/25622575/61460630-fee9bc00-a966-11e9-9165-bb9902be2390.png)

**Comment by stephenholleran** [comment]
This might be similar to issue #104

**Comment by Inder95** [comment]
@stephenholleran Solved both these issues. I have removed % signs from all of them for consistency.

![image](https://user-images.githubusercontent.com/23189856/61563460-eb744900-aa6b-11e9-9327-750858cac9b0.png)

**Comment by stephenholleran** [comment]
The axis labels seem wired and I've noticed it before. The label is rounded correct? See plot below and focus on sector 315-345. It has a value of above 3 but yet the plot is showing that it is below 3. I think this occurs in the freq_table plot too.

![image](https://user-images.githubusercontent.com/25622575/61592934-3d82af00-abd1-11e9-90a4-faa5eebd110c.png)

I think it comes from this code where after the max is set the levels are equidistant but then the label is rounded.

```python
    max_contour = (ext_data.max() + ext_data.std()).round()
    levels = np.linspace(0, max_contour+10-(max_contour%10), 10)
    ax.set_rgrids(levels, labels=['%.0f' % round(i) for i in levels], angle=0)
```

I changed this:
```python
ax.set_rgrids(levels, labels=['%.3f' % round(i,3) for i in levels], angle=0)
```
Which shows that the label lines are 3.333 and not 3.

![image](https://user-images.githubusercontent.com/25622575/61593141-a79c5380-abd3-11e9-9a3a-69426dc63dab.png)

There must be a way of rounding the labels for times when the max value is more than 6 (for 6 levels) and then go to 1 decimal or 2 decimals for when the max is around 1 e,g, plotting shear which has values around 0.2.

**Comment by stephenholleran** [comment]
@Inder95 make sure you pull as I fixed Shear with the new dist_by_dir_sector name.

**Comment by Inder95** [comment]
@stephenholleran Solved that issue. The same issue also would have occurred in plot_rose_with_gradient() so changed there too.

![image](https://user-images.githubusercontent.com/23189856/61739018-80848400-ad83-11e9-9e55-8c0d12a944b0.png)

![image](https://user-images.githubusercontent.com/23189856/61739735-f6d5b600-ad84-11e9-9daf-c0ba0a1af3d1.png)

**Comment by stephenholleran** [comment]
Hey. Just testing this out there. Not sure where the tick number 5 and line has gone on this one.

![image](https://user-images.githubusercontent.com/25622575/61831040-95851400-ae64-11e9-91c6-480404f3611a.png)

**Comment by stephenholleran** [comment]
This one is gone a bit weird going up in even numbers and then odd numbers.
![image](https://user-images.githubusercontent.com/25622575/61831247-2d82fd80-ae65-11e9-9d17-85d3e0ea87f8.png)

**Comment by Inder95** [comment]
> This one is gone a bit weird going up in even numbers and then odd numbers.
> ![image](https://user-images.githubusercontent.com/25622575/61831247-2d82fd80-ae65-11e9-9d17-85d3e0ea87f8.png)

Fixed

**Comment by stephenholleran** [comment]
> > This one is gone a bit weird going up in even numbers and then odd numbers.
> > ![image](https://user-images.githubusercontent.com/25622575/61831247-2d82fd80-ae65-11e9-9d17-85d3e0ea87f8.png)
> 
> Fixed

Will you be applying this fix to `freq_table()` too? Currently in branch #99 it is going up in odd integers and then swaps to even.

**Comment by Inder95** [comment]
> > > This one is gone a bit weird going up in even numbers and then odd numbers.
> > > ![image](https://user-images.githubusercontent.com/25622575/61831247-2d82fd80-ae65-11e9-9d17-85d3e0ea87f8.png)
> > 
> > 
> > Fixed
> 
> Will you be applying this fix to `freq_table()` too? Currently in branch #99 it is going up in odd integers and then swaps to even.

These changes are not in branch 99. In branch 169 (this branch) I have applied the changes to freq_table too. I will keep that in mind when we merge it to master.

**Comment by Inder95** [comment]
@stephenholleran resolved this issue, feel free to close. I will remove the pull request as these changes will be merged with branch 99.

**Comment by stephenholleran** [comment]
I'll close both this and the iss #99 off at the same time so I have this for reference until then.
