### ISSUE TITLE
[selective_average] issue with application of selective averaging 

### ISSUE THREAD

**Issue by ShaneBrightWind** [brightwind-dev/brightwind#179]
Issue when applying selective averaging for directions which are not the actual boom directions. Tried this to take out a wider area because of excessive lightning rod shadow. Tried it for 350 degrees and 140 degrees, and saw incorrect sectors used when viewing the sector ratio plot after the averaging was done. Did it for a sector width of 60 degrees. View recent SA site for data.

**Comment by stephenholleran** [comment]
Not an issue.
