### ISSUE TITLE
[offset_timestamps] adjusts the timestamp by a certain period

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#18]
This function will offset a timestamp or a series of timestamps by a certain datetime period e.g. 2 hours.

A use case would be to change the index of a DataFrame (which is in datetime format) by a certain number of hours to adjust for a time zone difference.

An extension of this use case is when only part of the DataFrame needs to be adjusted to account for daylight saving. In this case the start and end timestamps of the period to be adjusted will need to be sent as optional arguments. A check should also be performed to make sure no duplicate timestamps have consequentially been created.

A single timestamp or the index from a DataFrame or a DataFrame or Series could be sent to the function. 

The period to adjust by could be a datetime type or as is used in the '_coverage_' function:
>  - 2T, 2 min for minutely average
>  - Set period to 1D for a daily average, 3D for three hourly average, similarly 5D, 7D, 15D etc.
>  - Set period to 1H for hourly average, 3H for three hourly average and so on for 5H, 6H etc.
>  - Set period to 1MS for monthly average
>  - Set period to 1AS fo annual average

Suggested code:
```
def offset_timestamps(timestamps, delta_time_period, start_date=None, end_date=None):
```

This should be placed in the 'transform' section as it is transforming/changing the data.

Documentation and tests should be written by default as part of this function.

**Comment by Inder95** [comment]
@stephenholleran In the case where we offset only a slice of data frame we may create duplicate timestamps, what to do with them, do we use the new ones or the old ones, overwrite them, .. ?

**Comment by Inder95** [comment]
For now I have implemented it without the additional date range option, in my opinion user should send only the slice of data he wants to send. And it should be the users choice to how to merge it back so that he does not get locked up in  a system.

**Comment by stephenholleran** [comment]
How about the user sends the full time series and then the dates of the slice they want to change. Another input would be true/false to keep the newly created timestamps or keep the timestamps of the unchanged section of time series?

If this doesn't work then the docstring must include examples of how to merge the returned data back into their dataframe for both (or more) cases.

**Comment by Inder95** [comment]
Yeah that sounds good, we can give an option to overwrite the old timestamps with the new ones which by default will be false.

**Comment by stephenholleran** [comment]
Reviewing pull request #49 

The date_from; does that timestamp refer to the original dataset? Similar to date_to. Just update the :parm description to make it clear.

:param overwrite: 
What happens if duplicate timestamps are created like taking out a daylight saving adjustment? The example for that scenario keeps the unadjusted data and not the adjusted?
Instead of calling them 'old' timestamps maybe call them 'unadjusted'?
Update doc string to make it clearer.

Put a sentence at the start of the doc string outlining what the function does. E.g. "Offset timestamps by a certain time period."

What would a user do if they needed to adjust by a total of 1 week, 2 days, 3 hrs and 20 min? Would they convert all to min and use that? Maybe put in an example to show this?

Just looking at the code, if a DatetimeIndex is sent where is the overwrite accounted for?

**Comment by Inder95** [comment]
> Reviewing pull request #49
> 
> The date_from; does that timestamp refer to the original dataset? Similar to date_to. Just update the :parm description to make it clear.
> 
> :param overwrite:
> What happens if duplicate timestamps are created like taking out a daylight saving adjustment? The example for that scenario keeps the unadjusted data and not the adjusted?
> Instead of calling them 'old' timestamps maybe call them 'unadjusted'?
> Update doc string to make it clearer.
> 
> Put a sentence at the start of the doc string outlining what the function does. E.g. "Offset timestamps by a certain time period."
> 
> What would a user do if they needed to adjust by a total of 1 week, 2 days, 3 hrs and 20 min? Would they convert all to min and use that? Maybe put in an example to show this?
> 
> Just looking at the code, if a DatetimeIndex is sent where is the overwrite accounted for?

@stephenholleran  date_from is the date from the input data. Updated the docstring

If duplicated timestamps are created and overwrite is True the new adjusted timestamps (and their data) will remain and old timestamps would be dropped and when overwrite is False the unadjusted timestamps will remain and the adjusted ones will be dropped. Updated the doc string as per your suggestion.

The doc string describes how to enter offset for various periods like 1D, 1H, 1W, etc. But I think you didn't get that info because all the examples use min offset. I have updated the examples to include 1H, 1D.

DateTimeIndex follows the same principle as described above for any data. The code, looks different because in DateTimeIndex both the adjusted and unadjusted timestamps are the same programmatically unlike when both timestamps also have different data with them. In the case of DateTimeIndex we do not need to worry which one to drop, we only have to drop one of them and sort the values.

**Comment by stephenholleran** [comment]
> The doc string describes how to enter offset for various periods like 1D, 1H, 1W, etc. But I think you didn't get that info because all the examples use min offset. I have updated the examples to include 1H, 1D.
> 
I did get it. My question is a 'total' of 3hrs and 20min = 200 min. Do we need to convert to the lowest time period (i.e. min in this case) and then do the adjustment? Maybe an additional example showing this?

Your opt1, 2 and 4 examples all have two 'date_from' in the call.

**Comment by Inder95** [comment]
> > The doc string describes how to enter offset for various periods like 1D, 1H, 1W, etc. But I think you didn't get that info because all the examples use min offset. I have updated the examples to include 1H, 1D.
> 
> I did get it. My question is a 'total' of 3hrs and 20min = 200 min. Do we need to convert to the lowest time period (i.e. min in this case) and then do the adjustment? Maybe an additional example showing this?
> 
> Your opt1, 2 and 4 examples all have two 'date_from' in the call.

You can enter decimal values like 3.5H etc, added the example.
![image](https://user-images.githubusercontent.com/23189856/57327305-8a90d200-7106-11e9-8911-335446d6d477.png)

Also fixed the date_from mentioned twice.

**Comment by stephenholleran** [comment]
👍
