### ISSUE TITLE
add ipywidgets to requirements and setup.py

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#187]
Add ipywidgets to the requirements and setup.py files.

Use a python environment to check what else also needs to be added to these files.

Maybe reconsider the need for ipywidgets?

**Comment by Inder95** [comment]
Is there any function that needs ipywidgets?

**Comment by lucunnin** [comment]
ipywidgets is used to create progress bars for some of the shear functions. It could be removed, as it is not essential. 

IPython is also used by shear and needs to be added to the requirements file. 

ipython==7.4.0
ipywidgets==7.4.2 ( if it is to be kept)
