### ISSUE TITLE
[time_continuity_gaps] improve documentation and write tests

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#20]
- [x] Improve documentation to explain what the function does.
- [x] Add example usage.
- [x] Write test to pick out missing periods in a 10-min time series.
- [x] Write test to validate the lost days calculation

**Comment by stephenholleran** [comment]
@Inder95 How long do you recon it will take to complete these tasks?

Cheers

**Comment by Inder95** [comment]
The first two tasks should not take more than 20 minutes. The last two tests might take 45 min to an hour because you need to create series to test these.

**Comment by stephenholleran** [comment]
> The first two tasks should not take more than 20 minutes. The last two tests might take 45 min to an hour because you need to create series to test these.

2 hrs so to get it done completely?

**Comment by Inder95** [comment]
That should be a safe estimate (though I must mention I am not very good at giving time estimates). Let me know through slack if you are using it for estimating something crucial.
