### ISSUE TITLE
[time_continuity_gaps] Error in calculation of days lost

### ISSUE THREAD

**Issue by ShaneBrightWind** [brightwind-dev/brightwind#201]
Calculation of days lost by time continuity tool is incorrect. Time continuity includes the timestamp before and after the issue, both of these timestamps have data. Only the intervening period has lost data. However, the tool when calculating the data lost includes the timestamp before as being data lost.

**Comment by Inder95** [comment]
Looking into it.

**Comment by Inder95** [comment]
@ShaneBrightWind 
I fixed the issue, the problem was also that we were calculating the difference between available timestamps. In the case where only one was missing differencing adjacent two timestamps will give a difference of 2 timestamps instead of one. I have corrected but now when the only one timestamp is missing the table shows it in both to and from as below. Let me know if something else would be better there.
![image](https://user-images.githubusercontent.com/23189856/66206751-e7d68280-e6a8-11e9-99c1-7aed0eae16c7.png)

**Comment by ShaneBrightWind** [comment]
Yep that should be fine to show both as the same in the from and to columns

**Comment by stephenholleran** [comment]
**Original** 
![image](https://user-images.githubusercontent.com/25622575/66407891-e1684380-e9e5-11e9-8a7e-8592f6a22885.png)

**New**
![image](https://user-images.githubusercontent.com/25622575/66407975-03fa5c80-e9e6-11e9-8440-3ee8cc3cfa84.png)


- [ ] What's up with the warning?



Also, Inder, now that we have a version 1 I'm not sure we can commit directly into the master branch anymore.

**Comment by Inder95** [comment]
We are copying elements of a dataframe to itself, hence the warning can look into that. Also branches have version tags on them so I suppose pushing to the master shouldn't be a problem. Though I am not sure about this part of the workflow.

**Comment by stephenholleran** [comment]
![image](https://user-images.githubusercontent.com/25622575/66660549-53869580-ec3d-11e9-8d43-bc74031d8363.png)

@Inder95 I think I have found a problem with the fact you are using the time step to work out the timestamps that are missing. This is a case where the time steps is uneven.

You can see at the top the data has a timestamp at 11:50:01.
However, in the time gaps table it creates timestamps at 11:40:01 and 12:00:01. Not sure how exactly it is doing this but I would expect it is something to do with the uneven time steps.

**Comment by Inder95** [comment]
> ![image](https://user-images.githubusercontent.com/25622575/66660549-53869580-ec3d-11e9-8d43-bc74031d8363.png)
> 
> @Inder95 I think I have found a problem with the fact you are using the time step to work out the timestamps that are missing. This is a case where the time steps is uneven.
> 
> You can see at the top the data has a timestamp at 11:50:01.
> However, in the time gaps table it creates timestamps at 11:40:01 and 12:00:01. Not sure how exactly it is doing this but I would expect it is something to do with the uneven time steps.

Yeah you are write, in this case the time difference between adjacent timestamps at 11:50:01 is 11 minutes and the time period is actually 10 minutes, the algorithms recognises any difference greater than 10 minutes as missing data. I am not sure how we can include uneven timestamps in the algorithm. But the solution I think is to correct the timestamp 11:50:01.

**Comment by stephenholleran** [comment]
> I am not sure how we can include uneven timestamps in the algorithm.

Uneven timestamps should definitely be captured in this function. Calculation of the days missing will be difficult and what to show in the table but we need to do something.

> But the solution I think is to correct the timestamp 11:50:01.

I do not think that this is a solution for this function. We need to figure out a good way to handle this.

After these timestamps are identified then yes we will need to account for them either by removing the timestamp completely or round the timestamp. Both of these processes could be useful functions to implement.

**Comment by Inder95** [comment]
> Uneven timestamps should definitely be captured in this function. Calculation of the days missing will be difficult and what to show in the table but we need to do something.

I am not sure if any algorithm for finding missing timestamps for unevenly sampled data exists, but will look out for them. If you find any suggestions do let me know.

> I do not think that this is a solution for this function. We need to figure out a good way to handle this.
> 
> After these timestamps are identified then yes we will need to account for them either by removing the timestamp completely or round the timestamp. Both of these processes could be useful functions to implement.

A separate function will be an overkill here as pandas can change the index with single line of code:
```
df.rename(index={'2016-08-29 11:50:01 ' : '2016-08-29 11:50:00'}, inplace=True)
```

**Comment by stephenholleran** [comment]
@BiancaMorandi 

Should we be making this work for monthly data? I think this will be more difficult and may not be easily worked out.
