### ISSUE TITLE
[SpeedSort] If synthesize with setup data, it fails

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#203]
- [ ] `filter_by_coverage_threshold=False` doesn't exist in function `average_data_by_period`. Make sure that simply taking out this parameter is all that is needed to fix this.

- [ ] Why didn't a test pick this up?

**Comment by stephenholleran** [comment]
Also, the synthesize method doesn't seem to work as expected and is doing something funny. Maybe it is linked to me simply removing the `filter_by_coverage_threshold` to get this to work.

```
data = bw.load_csv(bw.datasets.demo_data)
Spd80mN_mth_plt, Spd80mN_mth_data = bw.monthly_means(data.Spd80mN, return_coverage=True)
display(Spd80mN_mth_plt)
Spd80mS_mth_plt, Spd80mS_mth_data = bw.monthly_means(data.Spd80mS, return_coverage=True)
display(Spd80mS_mth_plt)
```

![image](https://user-images.githubusercontent.com/25622575/67089296-27b86200-f19f-11e9-99a1-c89a8b946b64.png)

**Comment by stephenholleran** [comment]
```
ss_obj = bw.Correl.SpeedSort(data.Spd80mN, data.Dir78mS, data.Spd80mS, data.Dir78mS, '10min')
ss_obj.run(False)
data['Spd80mS_Synthesized'] = ss_obj.synthesize()['Spd80mS_Synthesized']
Spd80mS_Synth_mth_plt, Spd80mS_Synth_mth_data = bw.monthly_means(data.Spd80mS_Synthesized, return_coverage=True)
display(Spd80mS_Synth_mth_plt)
```
![image](https://user-images.githubusercontent.com/25622575/67089478-97c6e800-f19f-11e9-8dc1-5ba7129ee6aa.png)

**Comment by stephenholleran** [comment]
The result of the synthesize method is strange. First Spd80mS_Synthesized is cut off in Aug sometime?

Also, even though there is Spd80mN data available up till Nov-2016, this data is not used to synthesize the missing data at Spd80mS?

**Comment by lucunnin** [comment]
Spent a while looking into this. As far as I can tell, removing `filter_by_coverage_threshold` has no effect and is fine. 

It seems to me the reason for the Spd80mS_Synthesized data being cut off in August is because the reference direction data you are using, Dir78mS, only goes to the 11th of August. The '_predict' function used within synthesis concats the reference wind speeds and reference directions, so this results in the synthesized data only being calculated up to the date at which the direction measurements stop. If you try the exact code you have above with Dir38mS as the reference direction measurements instead,  Spd80mS_Synthesized will continue until near the end of November.

**Comment by stephenholleran** [comment]
> No tests picked it up as this parameter is simply not included in any of the tests for average_data_by_period. Its value was False by default, meaning it had no effect when removed apart from in instances where it was explicitly sent as a parameter, i.e. within synthesize.

Why didn't a test for synthesis pick it up? It should have failed if there was any test for synthesise?

**Comment by stephenholleran** [comment]
Fair enough on the Dir78mS not available.

**Comment by stephenholleran** [comment]
Can you test if Spd80mS was cut in half before been sent to the SpeedSort, would the .synthesize() synthesize all the data when Spd80mN is available? Paste the code in here. It should synthesize all the data where Spd80mN is available.

**Comment by lucunnin** [comment]
> > No tests picked it up as this parameter is simply not included in any of the tests for average_data_by_period. Its value was False by default, meaning it had no effect when removed apart from in instances where it was explicitly sent as a parameter, i.e. within synthesize.
> 
> Why didn't a test for synthesis pick it up? It should have failed if there was any test for synthesise?

There is no test for synthesise, or any of the correlation functions. 

> Can you test if Spd80mS was cut in half before been sent to the SpeedSort, would the .synthesize() synthesize all the data when Spd80mN is available? Paste the code in here. It should synthesize all the data where Spd80mN is available.

Sure, will try that now.

**Comment by Inder95** [comment]
> Can you test if Spd80mS was cut in half before been sent to the SpeedSort, would the .synthesize() synthesize all the data when Spd80mN is available? Paste the code in here. It should synthesize all the data where Spd80mN is available.

Speed Sort predicts the wind speeds and directional veers for each sector separately. So, even if you send whole Spd80mN without the whole direction, the method itself cannot synthesize the speed or veers.

**Comment by stephenholleran** [comment]
> Speed Sort predicts the wind speeds and directional veers for each sector separately. So, even if you send whole Spd80mN without the whole direction, the method itself cannot synthesize the speed or veers.

Hi Inder, not asking to not send the directions. Just cut Spd80mS in half and then send it as before. Will the function synthesise all of the Spd80mN data?

**Comment by stephenholleran** [comment]
> There is no test for synthesise, or any of the correlation functions. Should definitely write some?

Yeah, give it a shot.

**Comment by lucunnin** [comment]
If you cut Spd80mS in half, i.e. finishing around 2016/12/26,  using the same code as above, values are synthesised up to the last timestamp for the directional data. The limiting factor will still be the directional values. 

Again, If you replace Dir78mS with Dir38mS which has data covering the same period as Spd80mN, the data is synthesised for the entire period that Spd80mN is available. 

`data = bw.load_csv(bw.datasets.demo_data)
data = bw.apply_cleaning(data, r'C:\Users\lukec\brightwind_luke\brightwind\datasets\demo\demo_cleaning_file.csv')
Spd80mN_mth_plt, Spd80mN_mth_data = bw.monthly_means(data.Spd80mN, return_coverage=True)
display(Spd80mN_mth_plt)
Spd80mS_mth_plt, Spd80mS_mth_data = bw.monthly_means(data.Spd80mS, return_coverage=True)
display(Spd80mS_mth_plt)

ss_obj = bw.Correl.SpeedSort(data.Spd80mN, data.Dir78mS, data.Spd80mS[:47814], data.Dir78mS, '10min')
ss_obj.run(False)
data['Spd80mS_Synthesized'] = ss_obj.synthesize()['Spd80mS_Synthesized']
Spd80mS_Synth_mth_plt, Spd80mS_Synth_mth_data = bw.monthly_means(data.Spd80mS_Synthesized, return_coverage=True)
display(Spd80mS_Synth_mth_plt)`

**Comment by lucunnin** [comment]
> > There is no test for synthesise, or any of the correlation functions. Should definitely write some?
> 
> Yeah, give it a shot.

Grand, will add it as an issue so we can keep track of it.

**Comment by stephenholleran** [comment]
> If you cut Spd80mS in half, i.e. finishing around 2016/12/26, using the same code as above, values are synthesised up to the last timestamp for the directional data. The limiting factor will still be the directional values.
> 
> Again, If you replace Dir78mS with Dir38mS which has data covering the same period as Spd80mN, the data is synthesised for the entire period that Spd80mN is available.
> 
> ```
> data = bw.load_csv(bw.datasets.demo_data)
> data = bw.apply_cleaning(data, r'C:\Users\lukec\brightwind_luke\brightwind\datasets\demo\demo_cleaning_file.csv')
> Spd80mN_mth_plt, Spd80mN_mth_data = bw.monthly_means(data.Spd80mN, return_coverage=True)
> display(Spd80mN_mth_plt)
> Spd80mS_mth_plt, Spd80mS_mth_data = bw.monthly_means(data.Spd80mS, return_coverage=True)
> display(Spd80mS_mth_plt)
> ```
> 
> ```
> ss_obj = bw.Correl.SpeedSort(data.Spd80mN, data.Dir78mS, data.Spd80mS[:47814], data.Dir78mS, '10min')
> ss_obj.run(False)
> data['Spd80mS_Synthesized'] = ss_obj.synthesize()['Spd80mS_Synthesized']
> Spd80mS_Synth_mth_plt, Spd80mS_Synth_mth_data = bw.monthly_means(data.Spd80mS_Synthesized, return_coverage=True)
> display(Spd80mS_Synth_mth_plt)
> ```

Grand so.
