### ISSUE TITLE
[Correlation] Write test for correlation functions

### ISSUE THREAD

**Issue by lucunnin** [brightwind-dev/brightwind#210]
Write tests for all functions in correlation.py
- [x] test_CorrelBase

- [x] test_OrdinaryLeastSquares

- [x] test_OrthogonalLeastSquares

- [x] test_MultipleLinearRegression

- [x] test_SimpleSpeedRatio

- [x] test_SpeedSort

- [x] test_SVR

**Comment by stephenholleran** [comment]
Covered in issue #261
