### ISSUE TITLE
[time_continuity_gaps] warning msg regarding SettingWithCopyWarning

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#212]
What is this warning and can it be fixed?

![image](https://user-images.githubusercontent.com/25622575/69040338-8d3d7f80-09e5-11ea-92fb-4d6eeaf966e1.png)

**Comment by lucunnin** [comment]
I have tried to recreate this error on a virtual environment, using `pip install brightwind`, but can't. Can only presume the issue has been dealt with with a package update? Here are the packages that were installed today when I used `pip install brightwind`:

atomicwrites==1.3.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
brightwind==1.0.0
certifi==2019.9.11
chardet==3.0.4
colorama==0.4.1
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
idna==2.8
importlib-metadata==0.23
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.0
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
more-itertools==7.2.0
nbconvert==5.6.1
nbformat==4.4.0
nbsphinx==0.4.2
notebook==6.0.2
numpy==1.17.4
packaging==19.2
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
pluggy==0.13.0
prometheus-client==0.7.1
prompt-toolkit==2.0.10
py==1.8.0
Pygments==2.4.2
pyparsing==2.4.5
pyrsistent==0.15.5
pytest==5.2.4
python-dateutil==2.8.1
pytz==2019.3
pywin32==227
pywinpty==0.5.5
pyzmq==18.1.1
requests==2.22.0
scikit-learn==0.21.3
scipy==1.3.2
Send2Trash==1.5.0
six==1.13.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.7
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
wincertstore==0.2
zipp==0.6.0

**Comment by BiancaMorandi** [comment]
fixed in issue #201
