### ISSUE TITLE
[Correlation] Plots not being returned for some classes

### ISSUE THREAD

**Issue by lucunnin** [brightwind-dev/brightwind#214]
I have been noticing some issues with plots in some of the correlation classes. In the SpeedSort class and its subclass, SectorSpeedSort, nothing is returned or displayed when plot, plot_model or plot_wind_vane are called. This is an easy fix, I will do it. 
Classes for which plot is not working:

- [x] SVR

- [x] SpeedSort

- [x] SpeedSort.SectorSpeedModel

**Comment by stephenholleran** [comment]
Fixed in issue #261
