### ISSUE TITLE
[Correlation] OrthogonalLeastSquares.linear_func throws error

### ISSUE THREAD

**Issue by lucunnin** [brightwind-dev/brightwind#215]
I presume this function should be a static function and work in the same way as it does for the OrdinaryLeastSquares class?

![image](https://user-images.githubusercontent.com/46243826/69355158-55397500-0c4f-11ea-9057-7de7ffcb7aaa.png)

**Comment by Inder95** [comment]
Fixed this issue. Also we will never use the linear_func() this way. As the docstring has been added now this confusion won't arise.
