### ISSUE TITLE
[coverage] add example usage and add tests

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#22]
Modify doc string to say how this function works and how it is a wrap around function around 'average_data_by_period'.

Add example usage to the doc string.

Add tests using test data and compare to what would be expected.

Tests and improvements can also be applied to the 'average_data_by_period' function in transform.

**Comment by Inder95** [comment]
Stephen merged the pull request and I checked the website for changes. Everything seems fine.

**Comment by stephenholleran** [comment]
Can't this coverage function take a DataFrame and not just a Series?

**Comment by Inder95** [comment]
Yes it can take DataFrame too, I have added an example to docstring.
