### ISSUE TITLE
[apply_cleaning_windographer] time format issue

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#228]
apply_cleaning_windographer function is not taking into account the correct start and end time when data format is different than MM-DD-YYYY.

**Comment by stephenholleran** [comment]
@BiancaMorandi I think this is good. 

I rephrased the docstring for dayfirst to hopefully explain things better than the pandas docstring.

I also added it to `load_windographer_txt` as the tie format can be specified by the user when exporting from Windographer. I forgot to tag this issue in the commit msg so they don't show up here. If you could make sure that it works then I think we can merge this branch.
