### ISSUE TITLE
Online documentation - where is it gone?

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#24]
With the move to a public repo and the splitting of the documentation the Sphinx-docs seems to be missing?

**Comment by Inder95** [comment]
As now we host documentation in another repository, the brightwind-docs repository is effectively sphinx-docs. But the conf.py and makefile are still in the main repo/docs . In the readme for brightwind-docs repo, you can find instructions on how to setup these the repos on your system.

**Comment by stephenholleran** [comment]
> In the readme for brightwind-docs repo, you can find instructions on how to setup these the repos on your system.

There is nothing in the brightwind-docs repo? do you have it all in a local branch or something?

**Comment by stephenholleran** [comment]
ok so.

Can you update the readme in the main branch to explain how all this works as no one (including myself) will think to look in a branch? From my simple understanding branches are usually for changing things, not necessarily for holding permanent stuff. Therefore, i'll never think of looking in it.

**Comment by stephenholleran** [comment]
On the brightwind repo readme there is reference to Sphinx docs. There is no Sphinx docs folder in the brightwind repo anymore so can you update this readme to explain to a newbie what is required to create the documentation?

Cheers,
