### ISSUE TITLE
[OrdinaryLeastSquares] Error when input target data are monthly values

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#243]
When the input target data are monthly data the 'average_data_by_period' function called by 'OrdinaryLeastSquares' is not averaging data correctly. This is because the function estimates the target data timesteps to be of 31 days instead of 1M.
![image](https://user-images.githubusercontent.com/65398058/86330326-716aaf00-bc3f-11ea-87ae-22de6021c8df.png)
![image](https://user-images.githubusercontent.com/65398058/86330400-8ba48d00-bc3f-11ea-8791-c1e7241040b6.png)

**Comment by stephenholleran** [comment]
Fixed in iss #261
