### ISSUE TITLE
[Freqtab] Allow seasonality to be accounted for in the production of a freq table and tab file

### ISSUE THREAD

**Issue by ShaneBrightWind** [brightwind-dev/brightwind#244]
Currently if we produce a tab file from all data available. However, this data is often not in complete whole years, and may include as an example 2 winters and 1 summer. Therefore the distribution maybe overally biased to a specific season skewing the final results of modelling. 

To overcome this we will need to seasonally adjust the frequency table that is used for the generation of the tab file. BrightWind's old excel tools have this functionality in the mast_analysis tool. It can be found under the FT tab. This should be used as the basis for the scripting of this tool with associated plots and functionality.

**Comment by BiancaMorandi** [comment]
A merge request was sent for this

**Comment by stephenholleran** [comment]
- [ ] Should implement similar to MOMM process in #298, i.e. weighting the months by their calendar days.

- [ ] Account for when there is some missing direction data. Put in a separate bin called 'no_direction', when make a tab file distribute it across the sectors based on the frequency of occurrence of each sector.

- [ ] Link up with issue #269 where the tab file can be set to produce a certain mean wind speed.
