### ISSUE TITLE
[correlation] Add option to give aggregation_method as input to correlation function

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#245]
option to give aggregation_method as input to correlation function. The standard method implemented is aggregation_method  = mean but for solar analysis the aggregation_method needed is sum.

**Comment by stephenholleran** [comment]
From issue #262 


> Addd 'sum' as an aggregation method to Correl.OrdinaryLeastSquares function, for correlation of energy sums based on time series of power.
> 
> This would be useful as the present method involves separately using bw.average_data_by_period separately on two different datasets. Running multiple 'averaging' periods can then cause issues as summed time series are not properly aligned/synchronised.

**Comment by stephenholleran** [comment]
Not appropriate to apply to SimpleSpeedRatio or SpeedSort.
