### ISSUE TITLE
[Correl] Fix synthesize function bug when start time different between ref and target 

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#246]
synthesize function is not always giving a timestep regular timeseries when avg period is 3D, 7D or 15D. This is due to the fact that the start date for the target dataset is not the same than the ref dataset. The averaging is derived for different days for the two datasets and then the two averaged timeseries are concatenated...
![image](https://user-images.githubusercontent.com/65398058/93191329-4a9b1f80-f73c-11ea-9ec6-115c61943f65.png)

**Comment by stephenholleran** [comment]
Hi @BiancaMorandi,

Could you check to see if this problem is still the case since I updated the method the ref and target datasets are merged?

**Comment by stephenholleran** [comment]
> Could you check to see if this problem is still the case since I updated the method the ref and target datasets are merged?

It is. I'll take a look at the fix now.
