### ISSUE TITLE
Potential Shear.by_sector' methodology issue

### ISSUE THREAD

**Issue by AndyBrightWind** [brightwind-dev/brightwind#26]
Differences observed between sectoral shear outputs from bw.Shear.by_sector when compared to that of previous excel tool. Python library appears to be deriving shear for each timestep and then averaging those values within each sector, whereas excel macro groups speed data into sectors and then derives shear within each sector. 

![image](https://user-images.githubusercontent.com/43743490/51472377-2e7d8a00-1d71-11e9-8c3f-4d4690376664.png)

**Comment by Inder95** [comment]
@stephenholleran  this looks like a legitimate issue for discussion. Also look carefully the graph looks like it is rotated by one sector.

**Comment by Inder95** [comment]
@AndyBrightWind Can you also attach the tables of the shear for both these graphs?

**Comment by Inder95** [comment]
> > Also look carefully the graph looks like it is rotated by one sector.
> 
> The Excel graph is rotated by 1 sector. Sector 1 represents 0-30 degrees ("North is midway between first and last sectors". A better plot from the Excel Mast Analysis spreadsheet is shown below.
> 
> ![image](https://user-images.githubusercontent.com/25622575/51545602-39601980-1e5a-11e9-9b04-53408b806fbb.png)
> 
> This might be the difference, the sectors min and max?

Yeah I think its the same, having a look at the table of shear by sector would solve the problem. We can see if there are minor differences too.

**Comment by AndyBrightWind** [comment]
Thanks guys. It sounds like there were 2 issues here: 
1. I misunderstood the reference frame of the mast analysis sheet. 
2. the difference in methodologies mentioned in my original post. 

Indeed, most of the apparent difference came from the the first issue, as shown below. However, there are still some differences which would be worth agreeing for the library? Graph below and values attached.

[ShearByDirComparison.xlsx](https://github.com/brightwind-dev/brightwind/files/2791297/ShearByDirComparison.xlsx)

![image](https://user-images.githubusercontent.com/43743490/51672982-c4f5b980-1fc4-11e9-83cf-f6a59f799532.png)

**Comment by AndyBrightWind** [comment]
Once more with double the resolution (24 sectors) to allow a more direct comparison: 
![image](https://user-images.githubusercontent.com/43743490/51673699-92e55700-1fc6-11e9-890d-a7c383c43b7c.png)
[ShearByDirComparison.xlsx](https://github.com/brightwind-dev/brightwind/files/2791339/ShearByDirComparison.xlsx)

**Comment by Inder95** [comment]
@stephenholleran we can close this now.

**Comment by stephenholleran** [comment]
The difference was due to the sector boundaries been different in both methods.
