### ISSUE TITLE
[Correl] Add 'sum' as an aggregation method to Correl.OrdinaryLeastSquares function, for correlation of energy sums based on time series of power. 

### ISSUE THREAD

**Issue by AndyBrightWind** [brightwind-dev/brightwind#262]
Add 'sum' as an aggregation method to Correl.OrdinaryLeastSquares function, for correlation of energy sums based on time series of power. 

This would be useful as the present method involves separately using bw.average_data_by_period separately on two different datasets. Running multiple 'averaging' periods can then cause issues as summed time series are not properly aligned/synchronised.

**Comment by stephenholleran** [comment]
Similar to issue #245
