### ISSUE TITLE
[plot_freq_distribution] can plot only pd.series 

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#264]
In order to have multiple variables in the same freq distribution plot:
- [x] plot_freq_distribution function has to be modified to plot pd.Dataframe
- [x] dist function has to  be modified to accept pd.Dataframe and to give DataFrames as input to plot_freq_distribution
- [x] a function has to be generated to adjust color lightness automatically using the primary colors in COLOR_PALETTE

**Comment by stephenholleran** [comment]
colormap needs to be added to the requirements.txt and setup.py files.

And as a result easydev??
![image](https://user-images.githubusercontent.com/25622575/108922940-d2605080-762f-11eb-9227-484fa9eadfd7.png)

**Comment by stephenholleran** [comment]
This branch is so old that the merge request is requesting to merge into master. Could you change that to dev?

Maybe merge dev into it as there may be conflicts.

As a result I can't check this out too much but:

Can we make `adjust_color_lightness()` private if it isnot used by anything outside of plot.py? Just add an underscore to the start of it.

**Comment by BiancaMorandi** [comment]
> @BiancaMorandi I have added those libraries into the requirements and setup files.
> 
> I am looking at `bw.dist()` but I'm not seeing anything in the docstring to show how these changes are impacting this function. Remind me what the purpose of this is for and how does it enhance `bw.dist()`?

@stephenholleran I have updated doc strings for all functions relevant for this update and added a _bar_subplot function that can be called for all functions making bar plots. This function can make bar plots both vertically and horizontally.

**Comment by BiancaMorandi** [comment]
As for discussion with Stephen need to fix the below in _bar_subplot and plot_freq_distribution:
- [ ] have total_width as a percentage
- [ ] can we make single_width more intuitive?

**Comment by BiancaMorandi** [comment]
@stephenholleran I made the following changes. This is now ready for your review. Let me know if you have other comments.

- total_width input is now in percentage
- removed line_width input because it was not useful
- added min_bin_axis_limit and max_bin_axis_limit
- fixed docs strings for _bar_subplot and plot_freq_distribution
- added tests

**Comment by stephenholleran** [comment]
Hi @BiancaMorandi,

I have reviewed all the changes and suggest the following updates.

1. The `_sub_barplot` function assumes that all timestamped indexes will be formatted as monthly. `ax.yaxis.set_major_formatter(DateFormatter("%Y-%m"))` We should allow the user to send this format. We can default it to monthly.
2. ~~Allow the user to send their own tick label rotation for x-axis ticks. No need to rotate the index labels for horizontal bars.~~
3. See if you can fix the border offset, if possible
![image](https://user-images.githubusercontent.com/25622575/168855571-c00312ed-061b-4c94-9441-622c4db45e38.png)

4. Remove `plot_freq_distribution()` function from `dist()` and use `_bar_subplot` directly
   1. Put a DEPRECIATION (FutureWarning) notice on the `plot_freq_distribution` function

I have done number 2.

**Comment by BiancaMorandi** [comment]
@stephenholleran I have done points number 1 and 3 of your comments. For point 3 I have just added a limit to line_width to be between 0 and 1. There is not an easy fix otherwise.
