### ISSUE TITLE
[Correl] Add sector plots to the SpeedSort method

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#268]
Only the wind direction plot is working for SpeedSort. A wind speed scatter plot with fit line for each direction sector should also be plotted.

![image](https://user-images.githubusercontent.com/25622575/105736576-ddd73380-5f2c-11eb-8cc6-a96450658c66.png)

**Comment by stephenholleran** [comment]
Also validate synthesizing of data.

It looks like the direction sector bins are not calculated correctly when an uneven direction_bin_array is sent. It uses the number of sectors instead of the bin array.

`x['ratio'] = (x['dir'] - x['sec_mid_pt'])/(360.0/self.sectors)`

**Comment by BiancaMorandi** [comment]
> Also validate synthesizing of data.
> 
> It looks like the direction sector bins are not calculated correctly when an uneven direction_bin_array is sent. It uses the number of sectors instead of the bin array.
> 
> `x['ratio'] = (x['dir'] - x['sec_mid_pt'])/(360.0/self.sectors)`

This is solved in iss #282

**Comment by stephenholleran** [comment]
@BiancaMorandi 

![image](https://user-images.githubusercontent.com/25622575/109205937-2ccbef00-779f-11eb-84d3-4c8696c20f51.png)

Shouldn't the trendline be two straight lines as shown below? One going from the origin to the cut off (I think?) and then from there through the data.

![image](https://user-images.githubusercontent.com/25622575/109206071-508f3500-779f-11eb-8971-eeeb40a98cae.png)

**Comment by BiancaMorandi** [comment]
@stephenholleran the scatter plot by sector generated is what the SpeedSort function is doing at the moment. The prediction for ALL speeds is derived using the slope and offset of the line fitting speed data above cut-off and the line from cut-off to zero is not used for the prediction. If we want to use the line from cut-off to zero for the prediction of speeds < curr-off then we would need to update the prediction function used by speedsort.

**Comment by BiancaMorandi** [comment]
![image](https://user-images.githubusercontent.com/65398058/223537405-95d66f25-db7f-43df-8341-edbdaf3fada5.png)
needs to update predict timeseries given as input to plot to have sorted speeds to avoid the issue shown in plot above

**Comment by BiancaMorandi** [comment]
@stephenholleran I have solved the issue mentioned in comment above. This is ready for your to review.

**Comment by BiancaMorandi** [comment]
@stephenholleran I made the fixes you have requested for the `plot_scatter_by_sector` function docstring

**Comment by stephenholleran** [comment]
Thanks @BiancaMorandi .
