### ISSUE TITLE
[export_tab_file] send target wind speed we want tab file to have

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#269]
When there is less wind direction data compared to wind speed data the resulting tab file mean wind speed will be different to the wind speed mean sent to the function. 

The wind speed and direction data should be concat together and then NaNs dropped. The wind speed data is then scaled to the provided target wind speed resulting in a tab file with that mean.

**Comment by stephenholleran** [comment]
Hi @BiancaMorandi,

Some comments on the PR #361:

1. Can we explain more about what the method is to get the target mean freq table? It is an iterative process which converges on the target but will not reach it exactly, hence the 0.01% range. Explaining this more in the main body of the doc string might be useful for the user.
2. The name `var_series_mean_target` has the description _"Target value used to scale the mean of the frequency distribution.......The mean of frequency distribution is considered to match the target value........"_ This doesn't say anything about the 'var_series' as what is going on doesn't have anything to do with the input data. Would a better name be something like `freq_target_mean`, `freq_table_target_mean`, `freq_table_mean_target`, `mean_freq_table_target`, `target_freq_table_mean`, ??

That's it! 
Thanks!

**Comment by BiancaMorandi** [comment]
@stephenholleran I made the updates you have requested. Let me know if you have other comments.
