### ISSUE TITLE
[_scatter_plot] Generate function to get subplot and subplot by direction

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#272]
- [x] Modify [_scatter_plot] function to call another function generating the subplot
- [x] create function to plot scatter subplots by direction

**Comment by stephenholleran** [comment]
The legend should be shown if line_of_slope_1 is True.
![image](https://user-images.githubusercontent.com/25622575/106485904-fc977600-64a8-11eb-8091-384c8b4012d7.png)

**Comment by stephenholleran** [comment]
In the `_scatter_subplot` could you rename these parameters:
color_scatter to scatter_color
color_prediction to prediction_color
name_scatter_data to scatter_name
name_prediction to prediction_name
title_subplot to subplot_title

You get the idea.

We should probably have a attribute naming convention. I find it easier to find in the Notebook if I type scatter and then tab to find out everything associated with the scatter data. In this case scatter_color, scatter_name would come up.

It follows the convention for x, x_label, x_limits

**Comment by stephenholleran** [comment]
_scatter_subplot and plot_scatter contain `x_label`.

plot_scatter_wdir and plot_scatter_wspd `x_axis_title`.

Can we consolidate?

Similar for `y_label`.

**Comment by stephenholleran** [comment]
The tests fail.
![image](https://user-images.githubusercontent.com/25622575/106490992-4d5d9d80-64ae-11eb-869f-69596a2a0cc1.png)

**Comment by stephenholleran** [comment]
In `_scatter_subplot` and `plot_scatter` the attribute `prediction` is not intuitive as to what it does. Rename this to `trendline`.

As a result of its name it is always going to be a line => drop `prediction_marker='-'`.

**Comment by stephenholleran** [comment]
In `plot_scatter_by_sector` could the subplot titles be rounded to zero decimals and a space either side of '-'?
```
title_subplot=str(round(ratio_min, 0)) + ' - ' + str(round(ratio_max, 0))
```

**Comment by stephenholleran** [comment]
When calling the functions from the Correlation functions, instead of calling the trendline 'prediction' call it the 'regression line'.
