### ISSUE TITLE
[load_csv] pandas timestamp issue when timestamp is in format DD-MM-YYYY

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#28]
Pandas can automatically handle timestamps in yyyy-mm-dd (which should be used ALL the time) and mm-dd-yyyy but misinterprets when timestamp is in format dd-mm-yyyy.

**Comment by stephenholleran** [comment]
Code is already written in another service.

**Comment by Inder95** [comment]
@stephenholleran In which service is the code written?

**Comment by stephenholleran** [comment]
@jonesne92 I think I was thinking of one of your solutions to solve this problem with Pandas?
