### ISSUE TITLE
Upgrade to pandas version 1.1+

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#293]

**Comment by abohara** [comment]
@stephenholleran What would be the blockers for upgrading Pandas to recent version? Maybe able to help.

**Comment by stephenholleran** [comment]
@abohara 
This is funny, I actually just mentioned this to the team this morning. Seen as pandas is now up to 1.3 it is probably time to bit the bullet and upgrade it. I haven't actually ran brightwind with pandas 1.+ so I don't really know what is going to be involved. The blocker for us really is time so if you are able to help that would be great! @BiancaMorandi was going to start looking into it in Jan.

**Comment by abohara** [comment]
Thanks @stephenholleran . I will give it a go and send a pull request.
