### ISSUE TITLE
Documentation website - clean up the style format and include doc string content

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#30]
The documentations website style is not yet finalised. See link:
https://brightwind-dev.github.io/brightwind-docs/

Also, only the load functions are included. All other functions should be included whether or not their doc strings are finalised or not.

- [x] build wire frame from the Home page

- [x] build wire frames for the API section pages (landing page list, left menu, single page)

- [x] build wire frame for the Tutorial section pages (landing page, left menu, single tutorial page)

- [x] wire frame for Community - how to contribute text first

@Inder95 please add more functionality to this issue that I have missed?

![20190214_173659](https://user-images.githubusercontent.com/23189856/52872556-b83c2f80-3144-11e9-85e4-e83318efbb3d.jpg)

**Comment by Inder95** [comment]
Useful link: 
https://doughellmann.com/blog/2009/02/02/writing-technical-documentation-with-sphinx-paver-and-cog/

**Comment by stephenholleran** [comment]
Hold on Inder. The website looks shi*. We'll go over it when you come in later.

**Comment by Inder95** [comment]
> The documentations website style is not yet finalised. See link:
> https://brightwind-dev.github.io/brightwind-docs/
> 
> Also, only the load functions are included. All other functions should be included whether or not their doc strings are finalised or not.
> 
> * [ ]  build wire frame from the Home page
> * [ ]  build wire frames for the API section pages (landing page list, left menu, single page)
> * [ ]  build wire frame for the Tutorial section pages (landing page, left menu, single tutorial page)
> * [ ]  wire frame for Community - how to contribute text first
> 
> @Inder95 please add more functionality to this issue that I have missed?

![20190214_173659](https://user-images.githubusercontent.com/23189856/52872538-a65a8c80-3144-11e9-91d8-aaffd63dc3b3.jpg)

**Comment by stephenholleran** [comment]
@Inder95 can you remember what are the actions yet to be done on this?

One thing I noticed is that we have no 'Export' on the API page.

There is no left hand menu on the 'Tutorial' page. I suppose I need to actually write some content for the 'Getting Started' tutorial first. How do I go about doing this?

How can the website footer copyright year automatically change as the years go on?

**Comment by Inder95** [comment]
@stephenholleran  I have updated the documentation with export on the API page
Please check the docstring and if you are satisfied close this issue.

I could not get that left side menu and the +symbol for expandable lists. You might recall this when I asked for Neil's help.

The code was updated to show the current year in the footer.

**Comment by stephenholleran** [comment]
Still more to go the more I look at it.

- [ ]  The left menu disappears when you go into a function https://brightwind-dev.github.io/brightwind-docs/brightwind.export.export.export_tab_file.html#brightwind.export.export.export_tab_file That will probably be the same for Tutorials.

- [ ] When in a class like TI  you can't navigate to individual functions. https://brightwind-dev.github.io/brightwind-docs/brightwind.analyse.analyse.TI.html#brightwind.analyse.analyse.TI

- [ ] I wonder should Shear be like Correlation?

- [ ] If not the + symbol in the left menu to open them up then what about when you are in a function in Analyse that the other functions in Analyse are shown in the left menu? Preferably as a tree (but I know it can't be expandable.)

- [ ] Shouldn't the tutorials that are listed there at the moment be in the left menu? For the landing page we will have to come up with something home page.

**Comment by stephenholleran** [comment]
@Inder95 don't forget these?

**Comment by Inder95** [comment]
> @Inder95 don't forget these?

Yeah its on my to do list. I had spent a couple of hours trying to solve some of them but could not. I am planning to look at existing libraries to see how they code their documentation using sphinx.

**Comment by Inder95** [comment]
Some resources to look at:
- Article pointing to some resources for documentation:  https://realpython.com/documenting-python-code/#shared-projects

- Custom function for autodoc: https://github.com/inducer/hedge/blob/master/doc/manual/source/conf.py

- documentation with sidebars:
http://guides.dataverse.org/en/latest/api/index.html

- sphinx project examples:
http://www.sphinx-doc.org/en/master/examples.html#documentation-using-sphinx-bootstrap-theme

**Comment by stephenholleran** [comment]
@Inder95 making progress! Good stuff. Great that you solved the drilling down into the Classes. You may still be working on these but I'll just outline some comments so far:

- [ ] When in the API section can the side bar stay there when you drill down into a function?

- [ ] This branch has the new export_csv(). Can it be included?

- [ ] Tutorials; can we have the same side bar as for API and list all the tutorials in it. And similar to the API's it stays there when you navigate down into a tutorial.

- [ ] We should probably have a 'welcome to the tutorials' as the main landing page for Tutorials.
