### ISSUE TITLE
[basic_stats] issue with numpy version 1.20.1

### ISSUE THREAD

**Issue by SteveCordleBW** [brightwind-dev/brightwind#307]
Running basic_stats gives an error - it still works with numpy version 1.18.1, but not with the latest version (1.20.1). Error shown below and in attached image.

Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

![image](https://user-images.githubusercontent.com/91064627/136812867-af98cac8-49ad-4b8b-9407-2ffce0e6e15a.png)

**Comment by BiancaMorandi** [comment]
bug was not due to numpy version but probably to a bug of pandas when used with python version 3.8
