### ISSUE TITLE
[plot_sector_ratio] Generate sector ratio plot as subplot

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#309]
At the moment in the template notebook we plot the sector ratio only for the main spd and direction (the top one usually) but in this way we don't capture eventual booms/ mast twists as we don't look at other wind vanes. Need to change the plot_sector_ratio function to generate subplots.

**Comment by BiancaMorandi** [comment]
@rach185 can you please add few examples in the doc string of _plot_sector_ratio_subplot function?

**Comment by stephenholleran** [comment]
Hi @rach185,

There is a bit of inconsistency if the user wishes to return the data. In the doc string, and in other functions, the data is returned as a Dataframe. However with this, if more than one pair of anemometers is sent, a Dict is returned. I think this makes it more difficult for a user to use the returned data. Why not add a column to the Dataframe with the new distribution pair? 

Thanks

cc @BiancaMorandi

**Comment by stephenholleran** [comment]
@rach185 I did a little refactoring in commit [2166427](https://github.com/brightwind-dev/brightwind/commit/2166427793ae0554d289aec480ff9abfcb988349) on the return data piece.
Let me know that you are ok with this?

**Comment by rach185** [comment]
> 

Yes, that's much more concise. Thanks
