### ISSUE TITLE
Consistency importing matplotlib.pyplot and bw.analyse.plot

### ISSUE THREAD

**Issue by rach185** [brightwind-dev/brightwind#333]
The `plt` variable is used to import two different libraries in the plot.py and analyse.py scripts. 

In brightwind.analyse.plot.py import `matplotlib.pyplot as plt`. 
In brightwind.analyse.analyse.py `from brightwind.analyse import plot as plt`.

This inconsistency causes issues when editing functions or creating new functions which call existing functions across the two libraries. To fix this issue `plt` should be replaced by a new variable in either of the scripts. This change should be made to all functions in the script.

**Comment by stephenholleran** [comment]
Maybe change to `from brightwind.analyse import plot as bw_plt`?

**Comment by stephenholleran** [comment]
@rach185 can we now do this since the other issue has now merged?

cc @BiancaMorandi

**Comment by BiancaMorandi** [comment]
approved
