### ISSUE TITLE
[plot_freq_distribution] deprecate

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#335]
Following on from the discussion in https://github.com/brightwind-dev/brightwind/issues/264#issuecomment-1129130916

1. Remove plot_freq_distribution() function from dist() and use _bar_subplot directly
1. Put a DEPRECIATION (FutureWarning) notice on the plot_freq_distribution function

This is dependent on #333 been completed.

**Comment by stephenholleran** [comment]
Hi @BiancaMorandi ,

I ran this but didn't get a warning?
![image](https://user-images.githubusercontent.com/25622575/217245358-9eede345-b5e9-4dba-aa60-8d2a64ba6d24.png)

In the issue I mention a "FutureWarning". I wonder is that a more specific warning than just a warning?

**Comment by BiancaMorandi** [comment]
> Hi @BiancaMorandi ,
> 
> I ran this but didn't get a warning? ![image](https://user-images.githubusercontent.com/25622575/217245358-9eede345-b5e9-4dba-aa60-8d2a64ba6d24.png)
> 
> In the issue I mention a "FutureWarning". I wonder is that a more specific warning than just a warning?

@stephenholleran yes, you are right, according to https://docs.python.org/3/library/warnings.html, the DeprecationWarning is Base category for warnings about deprecated features when those warnings are intended for other Python developers and it is ignored by default, unless triggered by code in __main__. The FutureWarning is a base category for warnings about deprecated features when those warnings are intended for end users of applications that are written in Python and it is NOT ignored by default. I made the update.
