### ISSUE TITLE
[dist_of_wind_speed] doesn't allow to use different COLOR_PALETTE than the BW default

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#345]
dist_of_wind_speed function should be updated to take as input the colours - this is the case for current `master` but latest updates for `dev` don't allow this

**Comment by BiancaMorandi** [comment]
@stephenholleran as discussed, if you prefer that no color input is given to distribution speeds and that color list can be changed only changing the `bw.analyse.plot.COLOR_PALETTE.color_list ` then this issue can be closed and all changes disregarded. Let me know your thoughts.

**Comment by stephenholleran** [comment]
hi @BiancaMorandi 

Sorry, I am getting confused between all the PRs and issues.

OK, lets not allow the user to send colour direct in the function but they can change them in the colour palette.

The main problem was that the `_bar_subplot()` wasn't using the color_palette in the first place though? Is this fixed?

**Comment by stephenholleran** [comment]
> hi @BiancaMorandi
> 
> Sorry, I am getting confused between all the PRs and issues.
> 
> OK, lets not allow the user to send colour direct in the function but they can change them in the colour palette.
> 
> The main problem was that the `_bar_subplot()` wasn't using the color_palette in the first place though? Is this fixed in a different PR?

The colors are changed by setting the ` bw.analyse.plot.COLOR_PALETTE.color_list` and not by setting `bw.analyse.plot.COLOR_PALETTE.primary`.
