### ISSUE TITLE
[Shear.TimeOfDay] Pandas version 1.4.3 issue

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#347]
error below is raised for `bw.Shear.TimeOfDay` for 
![image](https://user-images.githubusercontent.com/65398058/183997355-5ce73a3a-f644-4dad-9c8f-2f9e71b6331e.png)
![image](https://user-images.githubusercontent.com/65398058/183997558-542d0d5f-2b37-4ad3-bc89-aa090a66a8a6.png)
![image](https://user-images.githubusercontent.com/65398058/183997704-249dd5ff-a56b-4958-a183-60d923fbd9af.png)

![image](https://user-images.githubusercontent.com/65398058/179838220-6e7f89c9-4c50-4b19-9a9f-541a660f23aa.png)
![image](https://user-images.githubusercontent.com/65398058/179838264-ee92d946-2a97-4a64-b611-13479d9e38f2.png)

**Comment by BiancaMorandi** [comment]
fixed issue for pandas v.1.0.* and tested with pervious versions (0.25.3)

**Comment by stephenholleran** [comment]
@BiancaMorandi 
Why can't you have a segment start time of 0? I would have thought it is allowed as it goes from 0 to 23 and doesn't include 24.

![image](https://user-images.githubusercontent.com/25622575/191324052-be857237-1888-452e-a6e5-a2ffd314030c.png)
