### ISSUE TITLE
[plot_timeseries] Use matplotlib instead of pandas for plotting

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#349]
We should update plot_timeseries to use Matplotlib instead of Pandas for plotting. This will allow user to have more flexibility in plotting.

Make basic updates below and then a separate issue will be raised for making major changes. 
- clip data based on user date_from and date_to input
- default set xaxis limits to min and max x value
- give option for setting min and max x and y limits
~~- give option for inputting format for x axis (and give example in docstring for time format options)~~
- set plotting similarly to scatter_subplot function

This update will allow to solve also issue raised from numpy=1.20.0 when pandas=0.25.3 (due to  'Using the aliases of builtin types like np.int is deprecated' in numpy -> https://numpy.org/devdocs/release/1.20.0-notes.html)  - #344

**Comment by BiancaMorandi** [comment]
The following updates were made:

1. Added `_timeseries_subplot` function. This function is taking the inputs below _timeseries_subplot(x, y, x_label=None, y_label=None, x_limits=None, y_limits=None, x_tick_label_angle=0,
                        line_marker_types=None, line_colors=COLOR_PALETTE.color_list, subplot_title=None,
                        legend=True, ax=None)`

**Comment by stephenholleran** [comment]
Merged.
#353
