### ISSUE TITLE
[twelve_by_24] Allow variable name as input for showing in plot

### ISSUE THREAD

**Issue by AndyBrightWind** [brightwind-dev/brightwind#36]
Suggestion: Allow the user to input a variable name and unit (eg 'Shear []') as arguments when calling the function. These strings are then presented alongside the colour bar in the plot instead of 'Variable'. This will be more intuitive for the reader when the plot is inserted into reports. Thanks.

**Comment by Inder95** [comment]
@AndyBrightWind Good suggestion Andy, hope it solves your problem.
