### ISSUE TITLE
[freq_table] Bug on deriving freq table when freq_as_percentage=True and seasonal_adjustment=True

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#365]
**Describe the bug**
At the moment it is possible to derive a freq table if freq_as_percentage=True and seasonal_adjustment=True. This shouldn't be possible as a table of counts shouldn't be weighted averaged to apply a seasonal adjustment.

an error should be raised
update the description for freq_as_percentage to say that it won't work with seasonal_adjustment.

**Comment by stephenholleran** [comment]
@BiancaMorandi 

From PR #366 

> * added ValueError when aggregation method is  set to 'count' for `_get_dist_matrix_by_dir_sector_seasonal_adjusted`

Can this function be used for max, min, std or an other aggregation_method?

**Comment by BiancaMorandi** [comment]
@stephenholleran yes it can be used for max, min, std or any other stats that are not summing up the monthly values. e.g sum, count aggregation methods are not giving the correct results when the seasonal adjustment is applied. 

The seasonal adjusted function is deriving the distribution of the data for each calendar month, applying the input aggregation method for each calendar month (i.e. all January), and then the 12 months of the year are weighted averaged. This means that if I have data for Jan 2020 and Jan 2021 an the aggregation methods are as below then I will have a different result:
- aggregation method is 'mean' then the Jan distribution is the mean of the 2 Januaries and the seasonal adjusted distribution is the mean of the mean for each calendar month
- aggregation method is 'count' or 'sum' then the Jan distribution is the sum of counts or the sum of values over the 2 Januaries and the seasonal adjusted distribution would be the mean of the total count or total sum (for multiple years and same months) for each calendar month. This result won't make sense and this is why a warning is raised.

**Comment by stephenholleran** [comment]
ok, thanks.
Can you throw a warning/error if 'sum' is also sent?
Thanks.

**Comment by BiancaMorandi** [comment]
@stephenholleran done

**Comment by BiancaMorandi** [comment]
merged
