### ISSUE TITLE
[_ColorPalette] Restructure Class and remove hardcoded shades of colors

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#381]
ISSUE
`_ColorPalette` Class lists many colors without having any link between each others:
 - e.g. `self.primary_10` is a hardcoded color that is 10% of the primary color -> it would be better for this color to be defined in function of `self.primary` and not to be hardcoded
 - a change of colors listed by `self.color_list` doesn't have any impact on the inputs colors used for this list e.g `self.primary `, `self.secondary` etc... and viceversa
 - a change of self.primary `, `self.secondary` etc. doesn't have any impact on `self._color_map` and viceversa

UPDATES TO MAKE
This Class should be improved to have dependencies between  `self.color_list`, `self._color_map` and each single color and between primary colors and derived shades of the same color.

**Comment by stephenholleran** [comment]
Thanks @BiancaMorandi !
