### ISSUE TITLE
[slice_data] if date_to is in date format then is taking beginning of day

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#385]
When date_to is a date (e.g 2017-05-31), the `slice_data` function converts the date string into a datetime and therefore adds 00:00:00 to the date making it stop at 2017-05-31 00:00:00.

![image](https://user-images.githubusercontent.com/65398058/226941052-220193e4-254c-4e99-a9b2-8f79fd11ccff.png)

**Expected behavior**
Data should be taken up to the end of the day. 

Note that:

- for brightdata we take 'less than' using `df = df[df.index < to_date]`, e.g if date_to = '2017-06-01' then data is taken up to '2017-05-31 23:59:59' 
- pandas is by default taking the end of the day if input is a date. e.g if date_to = '2017-06-01' then data is taken up to '2017-06-01 23:59:59' 

Doing 'less than' the user does not need to remember how many days are in a particular month and so could just use '2017-06-01'. Whether we do 'less than' or not, the slice_data isn't consistent with that or even pandas so we need to change it.

**Comment by BiancaMorandi** [comment]
Other functions using `pd.to_datetime()`  and therefore having a similar issue are below:

- `offset_timestamps` function, if date_to is a date (e.g 2022-01-01) then the offset is applied up to 00:00 of the date (e.g 2022-01-01 00:00 ) and not up to the end of the day (e.g 2022-01-01 23:50)
- ' bw.load.load._LoadBWPlatform.get_data(meas_loc_uuid, from_date=None, to_date='2021-05-01')', gets data up to '2021-05-01 00:00)

**Comment by BiancaMorandi** [comment]
@stephenholleran we have discussed this issue internally and agreed to use the 'less than' method for date_to.

**Comment by stephenholleran** [comment]
Thanks @BiancaMorandi !
