### ISSUE TITLE
[calc_air_density] calculate air density based on temperature and pressure values given

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#39]
Add a new function that will calculate the air density based on a given temperature and pressure. Additional functionality can be to return a scaled up air density if given a site altitude and a reference altitude.

Previous code written in javascript to do this as part of a web app.
```javascript
function getAirDensity()
	{                
		//var temp=new number;
		var Kfactor=273.15;	// convert deg C to Kelvin.
		var R=286.9;	// specific gas constant for humid air J/(kg.K).
		var lapseRate = -0.113;	// air density lapse rate kg/m^3/km
		var temp = Number(window.document.getElementById('temp').value);
		var pressure = Number(window.document.getElementById('pressure').value);
		var elevationRef = Number(window.document.getElementById('elevationRef').value);
		var elevationSite = Number(window.document.getElementById('elevationSite').value);
		temp = temp + Kfactor;
		pressure = pressure*100;
		var refAirDensity = pressure/(R*temp);
		var siteAirDensity = (refAirDensity + (((elevationSite-elevationRef)/1000)*lapseRate)).toFixed(3); // round to 3 decimal places.
		window.document.getElementById('airDensityAnswer').innerHTML=siteAirDensity;
    }     
```

**Comment by stephenholleran** [comment]
In Python

```python
Kfactor=273.15 # to convert deg C to Kelvin.
R=286.9    # specific gas constant for humid air J/(kg.K).
lapseRate = -0.113    # air density lapse rate kg/m^3/km
temp = bw.momm(merra2_node_df[0].data.Tmp_2m_degC)
pressure = bw.momm(merra2_node_df[0].data.Prs_0m_hPa)
elevationRef = 50
elevationSite = 130
temp = temp + Kfactor
pressure = pressure*100
refAirDensity = pressure/(R*temp)
siteAirDensity = round(refAirDensity + (((elevationSite-elevationRef)/1000)*lapseRate), 3)
```

**Comment by Inder95** [comment]
@stephenholleran Pushed basic code pertaining to calc_air_density(). Seems to me that there should be more to docstring, please have a look and let me know.

**Comment by stephenholleran** [comment]
Made some changes but there is more to clean up after me.

The function should be able to take a single value of temperature or pressure not just a series or dataframe. For my own messing around I commented out the momm calculation. That can be put back in but there is functionality to be added to determine is Series or single value. Actually thinking about it what should be returned is a time Series (or DataFrame) of air densities when both the temperature and pressure are present. The user can average whatever way they wish from the Series they get back.

The air density can be extrapolated from one elevation to the other by using the lapse rate. Both the elevation of the reference and the elevation of the site need to be given so if only one is given then send a msg back saying one of them is missing. A msg should also be sent if a negative elevation is sent.

The function breaks if either the elevations are still set to None so you need to put a test in there to check. You can either set both of them to 0 (the same elevation) and apply the lapse rate all the time or not.

Examples for using single values should be provided as well as sending a Series as you have. Also setting an elevation when the single values are given e.g.
`bw.calc_air_density(15, 1013, elevation_ref=0, elevation_site=200)`

Tests that can be could be:
`bw.calc_air_density(15, 1013)` = 1.225
`bw.calc_air_density(15, 1013, elevation_ref=0, elevation_site=200)` = 1.203
`bw.calc_air_density(15, 1013, elevation_ref=0)` = error msg text
`bw.calc_air_density(15, 1013, elevation_ref=0, elevation_site=-200)` = error msg text
`bw.calc_air_density([15, 12.5, -5, 5, 23], [1013, 990, 1020, 900])` = [1.225, 1.208, 1.326, 1.059]

**Comment by stephenholleran** [comment]
@Inder95 Is this one complete?

**Comment by Inder95** [comment]
> @Inder95 Is this one complete?

Yes we I will merge the branch.
