### ISSUE TITLE
[plot_shear_by_sector] Raise an error when at least on inf value is given as input

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#397]
**Describe the bug**
When running the following code an error is raised if at least one roughness value, given as input to `plot_shear_by_sector` function, is inf. The error raised is reported in screenshot below. 
`shear_by_sec_obj = bw.Shear.BySector(data_clnd[wspd_shear_cols], wspd_shear_heights_displaced, 
                                     data_clnd[wdir_main], calc_method=shear_calc_method, sectors=12)`

![image](https://github.com/brightwind-dev/brightwind/assets/65398058/550e6878-4919-4a44-9dd9-82bf971731d2)

**Expected behavior**
Error should not be raised and plots should be generated with nan instead of inf values.

**Comment by stephenholleran** [comment]
Hi @BiancaMorandi,

Could you run that line of code again and screenshot the result now that it is fixed?

The changes look good.

**Comment by BiancaMorandi** [comment]
@stephenholleran see screenshot below showing succesfull plot for same roughness values used as input to plot shear by sectors function.
![image](https://github.com/brightwind-dev/brightwind/assets/65398058/e194f31f-7c66-4a3c-af7e-1adf09f60932)
