### ISSUE TITLE
[time_continuity_gaps] Update to doc string to give wider understanding of function.

### ISSUE THREAD

**Issue by ShaneBrightWind** [brightwind-dev/brightwind#425]
The time continuity gaps function looks for gaps in the timestamp. However, if it also finds a line of data that has all NaNs, it considers this to also be a timestamp gap, even though there is a line of NaN data. This is not clear from the doc string. It is recommended that the following text is added to the doc string of the function.

"It should be noted that were a timestamp exists for a row of data, but where all values in that row are NaN's, this row will also be consider a time continuity gap as it represents a break in the data and ordinary functioning of the logging unit."

**Comment by stephenholleran** [comment]
@ShaneBrightWind thanks for the feedback.

Do you want to implement it and create a pull request into the 'dev' branch for this change?

**Comment by ShaneBrightWind** [comment]
That has now been addressed @stephenholleran , branch created for your review
