### ISSUE TITLE
[SectorRatio.by_sector] plotting warning message relating to RGB

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#44]
Warning msg

_'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points._

What needs to be done to remove this warning? I am assuming it is something to do with matplotlib.

![image](https://user-images.githubusercontent.com/25622575/56205530-f1f4be00-6041-11e9-8e5c-1e2383df104f.png)

**Comment by Inder95** [comment]
Strange I don't get that warning in my system
![image](https://user-images.githubusercontent.com/23189856/56445265-41621500-62f4-11e9-8b30-e93081e7d06b.png)

**Comment by stephenholleran** [comment]
I get it with the demo_site_data too.

![image](https://user-images.githubusercontent.com/25622575/56576241-bfa60c00-65bf-11e9-9449-b96d30491545.png)

**Comment by Inder95** [comment]
@stephenholleran Made a small change, let me know if it works. I can't check here as the warning is not shown in my system.

**Comment by stephenholleran** [comment]
That worked.

![image](https://user-images.githubusercontent.com/25622575/57036497-5ae85280-6c4c-11e9-8671-5331db2749c2.png)

**Comment by stephenholleran** [comment]
Just noticed. The caption at the bottom isn't centered anymore? It is not centered in the previous image either as you can see above. They were centered right?

**Comment by Inder95** [comment]
It was not centered earlier. But it was a good suggestion so I implemented it. Though not perfect but I could get it approximately centered (it was difficult to find a solution for polar plot). The results are below:
![image](https://user-images.githubusercontent.com/23189856/57091217-90e70e80-6d00-11e9-98ea-67fef46ed19d.png)

**Comment by stephenholleran** [comment]
Why not use `fig.text()` as it has `ha='center'`?

Push the text up closer to the plot as there is too big of a gap between the plot and text.

I notice that the caption is only written when both boom directions are given. There is a use case where one of the anemometers is top mounted which therefore has no boom orientation. In this case we only plot the one boom and not the top mounted but we still want the caption to say which boom is which anemometer. Could the caption text be constructed to say either:
   '* Plot generated using Spd60mN (yellow green boom) divided by Spd60mTop (top mounted)' or
   '* Plot generated using Spd60mTop (top mounted) divided by Spd60mN (blue boom)'?
There are if statements there already to use.

You can use the 'boom_dir_X' default of -1 to default to top mounted.

Update the doc string to explain all this and add examples showing a normal use and a top mounted use?

You have the 'boom_dir_X' doc string default as 0 when it should be -1.

**Comment by Inder95** [comment]
> Why not use `fig.text()` as it has `ha='center'`?
> 
> Push the text up closer to the plot as there is too big of a gap between the plot and text.
> 
> I notice that the caption is only written when both boom directions are given. There is a use case where one of the anemometers is top mounted which therefore has no boom orientation. In this case we only plot the one boom and not the top mounted but we still want the caption to say which boom is which anemometer. Could the caption text be constructed to say either:
> '* Plot generated using Spd60mN (yellow green boom) divided by Spd60mTop (top mounted)' or
> '* Plot generated using Spd60mTop (top mounted) divided by Spd60mN (blue boom)'?
> There are if statements there already to use.
> 
> You can use the 'boom_dir_X' default of -1 to default to top mounted.
> 
> Update the doc string to explain all this and add examples showing a normal use and a top mounted use?
> 
> You have the 'boom_dir_X' doc string default as 0 when it should be -1.
 I had earlier looked at fig.text() but it is easier to do it with annotate because the xy position of the text can then be determined using a fraction of axes coordinates but for fig.text() that feature did not exist. the 'ha'=center is not the alignment of the text w.r.t. figure but with respect to the position we specify in the input.

As suggested the text has been pushed closer to the graph.
![image](https://user-images.githubusercontent.com/23189856/57391229-f8480700-71b5-11e9-8526-9d9ef8d8e415.png)

The case involving the top mount boom has also been implemented:
![image](https://user-images.githubusercontent.com/23189856/57392301-5544bc80-71b8-11e9-8674-df48ba4d355a.png)

Updated the docstring too.

**Comment by stephenholleran** [comment]
> I had earlier looked at fig.text() but it is easier to do it with annotate because the xy position of the text can then be determined using a fraction of axes coordinates but for fig.text() that feature did not exist. the 'ha'=center is not the alignment of the text w.r.t. figure but with respect to the position we specify in the input.

I made a change by using `horizontalalignment` and setting the x to 0.5 (the middle). I know someone is going to put in a big long wind speed column name that will make this look bad if we don't try and center align.

I also refactored the boom options. Not sure if it is any better but there's less doubling up of doing the same thing.

Can you put in the `:type` in the doc string for `plot_sector_ratio` as I have no idea what the parameters are supposed to be?

Can you put in the doc string example in `bw.SectorRatio.by_sector` how the `direction_bin_array` works?

**Comment by stephenholleran** [comment]
@Inder95 don't forget about this :)
