### ISSUE TITLE
[freq_table] doesn't show the variable labels in the plot from 'plot_wind_rose_with_gradient'

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#46]
When a different variable other than wind speed it is possible to send var_bin_labels. These seem to be processed correctly in deriving the data to plot however the var_bin_labels are not sent to the sub function 'plot_wind_rose_with_gradient'. The var_bin_labels there are hard coded for wind speed. Is it possible to use the gradient based on the var_bin_labels sent or the var_bin_array sent?

**Comment by Inder95** [comment]
@stephenholleran In 'plot_wind_rose_with_gradient' **bins hard coded  are different from var_bin_array** which decides the bins in frequency table. This was because we needed only 6 color bins in our wind rose. 
**How does adding an extra variable sound, 'plot_bins' to decide how many bins to be used in wind rose color?**

But if we decide to use the same binning in wind rose color as in frequency table we will have much more colors in the plot. When we first wrote that function the plot was not very informative because there were loads of colors on the rose.

**Comment by Inder95** [comment]
That is a valid bug, I will have to look into it. plot_wind_rose_with_gradient() is specifically tuned to 6 speed bins, complete code will be changed here.

**Comment by stephenholleran** [comment]
> That is a valid bug, I will have to look into it. plot_wind_rose_with_gradient() is specifically tuned to 6 speed bins, complete code will be changed here.

OK, sounds like that error is linked with the main point of this issue. We will have to have a good think about it. Your suggestion of plot_number_bins might be the answer. What do you think of my suggestion of use_var_bin_labels_in_plot=False?

**Comment by Inder95** [comment]
> > That is a valid bug, I will have to look into it. plot_wind_rose_with_gradient() is specifically tuned to 6 speed bins, complete code will be changed here.
> 
> OK, sounds like that error is linked with the main point of this issue. We will have to have a good think about it. Your suggestion of plot_number_bins might be the answer. What do you think of my suggestion of use_var_bin_labels_in_plot=False?

The plot_bins would be an array like the var_bins. But you are right this makes the bin labels more cumbersome. The problem here is that we need those 5 colors for the wind rose plot. If we relax this assumption (as others might not find it useful) we have a much simpler function. We can keep the other function which is custom to our needs separately.

If we decide to go ahead I think an array of plot_bins might be useful. That also covers the case you suggested use_var_bin_labels_in_plot=True, when the user needs this he can just pass the same array as she passed to var_bins.

**Comment by stephenholleran** [comment]
OK go with your suggestion but I'm not too sure how it will work. Keep in mind the user and making it as user friendly as possible!

**Comment by Inder95** [comment]
@stephenholleran  Here is more generic function fro plotting wind rose. I added plot_bins and plot_labels to decide the bins while plotting and the use cases are below. Let me know your opinion and also review the docstring.

- The var_bin_array now works
![image](https://user-images.githubusercontent.com/23189856/58381348-1e421980-7fb4-11e9-9a76-d202419ffce4.png)
![image](https://user-images.githubusercontent.com/23189856/58381356-2a2ddb80-7fb4-11e9-91e4-87757e28f841.png)

- Custom direction bins also work:
![image](https://user-images.githubusercontent.com/23189856/58381372-45005000-7fb4-11e9-9d6a-1d867aefbfb3.png)
![image](https://user-images.githubusercontent.com/23189856/58381375-521d3f00-7fb4-11e9-9275-dc5750e4a13b.png)

- We choose 6 bins for plotting of almost equal widths by default ( the extra rows added to the last bin)
![image](https://user-images.githubusercontent.com/23189856/58381399-a0324280-7fb4-11e9-93e5-414e0b33dd32.png)

- The plot we had earlier now becomes just a way of calling this function, that way has been mentioned in the docstring:
![image](https://user-images.githubusercontent.com/23189856/58381415-c35cf200-7fb4-11e9-942b-3ee15af0bb83.png)

**Comment by stephenholleran** [comment]
Some questions:

1. If a `direction_bin_array` is sent, does this overrule the `sectors` argument? If so, update doc string.

1. Why did you change the default behaviour? I think the way we had the wind rose plotted previously was better.

1. Why does this not work for me?
```python
temp_rose, temp_freq_tab = bw.freq_table(data.T2m, data.Dir78mS, var_bin_array=[-10, 0, 10, 20], 
                                         var_bin_labels=['low', 'mid', 'high'], 
                                         plot_bins=[-10, 0, 10, 20],
                                         plot_labels=['low', 'mid', 'high'], 
                                         return_data=True)
```
```python
AttributeError: 'pandas._libs.interval.Interval' object has no attribute 'overlaps'
```

4. `distribution_by_direction_sector` and `freq_table` have a lot of duplication. Can these be refactored to share the duplicated code.

With the duplication above there is also duplication for the basic `plot_wind_rose` as outlined in iss #52. I think we need to take a step back and think about the use cases for all of these? Are you able to start writing some use cases down here?

**Comment by Inder95** [comment]
> 1. If a `direction_bin_array` is sent, does this overrule the `sectors` argument? If so, update doc string.
I did mention that, but have changed the statement in docstring to better reflect this.

> 2. Why did you change the default behavior? I think the way we had the wind rose plotted previously was better.
As I mentioned, the previous case is now just a special case of this new function, to reflect that I showed the previous case as an example in the docstring so you can copy paste easily. As you think it was better, I changed the default arguments to that special case.

> 3. Why does this not work for me?
> 
> ```python
> temp_rose, temp_freq_tab = bw.freq_table(data.T2m, data.Dir78mS, var_bin_array=[-10, 0, 10, 20], 
>                                          var_bin_labels=['low', 'mid', 'high'], 
>                                          plot_bins=[-10, 0, 10, 20],
>                                          plot_labels=['low', 'mid', 'high'], 
>                                          return_data=True)
> ```

> ```python
> AttributeError: 'pandas._libs.interval.Interval' object has no attribute 'overlaps'
> ```
Works for me, but I just checked that the feature 'overlaps' is new in pandas version 0.24.0. (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Interval.overlaps.html) I have updated the requirements to reflect that.
![image](https://user-images.githubusercontent.com/23189856/58423596-66813a80-808d-11e9-9cbb-f45552c8cbb4.png)

> 1. `distribution_by_direction_sector` and `freq_table` have a lot of duplication. Can these be refactored to share the duplicated code.
They had a few lines duplicated were we get the `direction_binned_series`  I have refactored the code to reflect that.

> With the duplication above there is also duplication for the basic `plot_wind_rose` as outlined in iss #52. I think we need to take a step back and think about the use cases for all of these? Are you able to start writing some use cases down here?
I have been thinking about how else can we expose plot_wind_rose to the user. But I will not be worried about a few lines of code duplicated here and there. If having a few extra lines of code makes the functions more independent of each other and the library more modular, its worth sacrificing a  few bytes.
(Listing the use cases is a good idea because most of these functions were written with very specific use cases in mind, but now we are generalizing it)

Also there are too many functions for distribution causing this confusion
- `distribution`
-  `distribution_by_wind_speed`
- `distribution_by_dir_sector`
-  `freq_table`

Way we look at it is; there are two broad use cases:
1. Distributions involving direction
    - If both distribution of direction and the other variable is needed we use `freq_table`
    - If only distribution by direction is needed we use `distribution_by_dir_sector`
2. Distributions not involving direction
    - If both the variables are distributed use `distribution`
    - For special case of wind speed we use `distribution_by_wind_speed`, this could be removed 

For this case here is my suggestion:
Following the convention of the library we can return the rose with distribution_by_direction_sector as described in the comment https://github.com/brightwind-dev/brightwind/issues/52#issuecomment-491059912

**Comment by stephenholleran** [comment]
> Also there are too many functions for distribution causing this confusion
> 
> * `distribution`
> * `distribution_by_wind_speed`
> * `distribution_by_dir_sector`
> * `freq_table`
> 
> Way we look at it is; there are two broad use cases:
> 
> 1. Distributions involving direction
>    
>    * If both distribution of direction and the other variable is needed we use `freq_table`
>    * If only distribution by direction is needed we use `distribution_by_dir_sector`
> 2. Distributions not involving direction
>    
>    * If both the variables are distributed use `distribution`
>    * For special case of wind speed we use `distribution_by_wind_speed`, this could be removed
> 
> For this case here is my suggestion:
> Following the convention of the library we can return the rose with distribution_by_direction_sector as described in the comment [#52 (comment)](https://github.com/brightwind-dev/brightwind/issues/52#issuecomment-491059912)


Yes, I broadly agree.  Below is a scribble that is helping me think about it.

![20190527_165132](https://user-images.githubusercontent.com/25622575/58430165-3000eb00-80a0-11e9-8059-0ac5f9a3efc6.jpg)

The `freq_table` is the main function.
1. From this a wind rose (graded or not) can be derived from it by summing up each direction column. This should also be produced if we use the function `distribution_by_dir_sector` (graded or not).

1. Also a frequency distribution can be derived by summing up the rows. This should also be produced if we use `distribution_by_wind_speed` which itself can simply just call `distribution` with specific parameters for wind speed binning. `distribution` is simply a histogram that can take 1 or 2 variables. 

1. And (we haven't thought of this before) a matrix of plots showing the frequency distribution for each of the direction sectors.

I am not sure how the `freq_table` can return 3 different plots? Or if we even want it to.

`distribution_by_wind_speed` and `distribution_by_dir_sector` should be able to take the `freq_table` data or timeseries.

`freq_table` itself is possibly just a `distribution_matrix` where 2 variables can be sent along with all the bin arrays. An example could be a matrix of shear and turbulence values. Also, a 3rd variable could be sent where the mean, max, min, std, etc could be calculated for it.

# posting this now but will come back and edit #

**Comment by Inder95** [comment]
As we both agree on returning a rose from `distribution_by_dir_sector`, the changes were made. Waiting for you to complete the suggestions above :)

**Comment by stephenholleran** [comment]
An example of the basic `distribution` function with the `distribution_by_wind_speed` wrapping around it.

```python
# If plotting against itself then no need to send the same series twice as in distribution 
# of wind speed.
# Instead of var2_bin_array and var2_bin_labels can these be var1 to make the above work? 
def distribution(var1_series, var2_series=None, var1_bin_array=[-10, 0, 10, 20, 30],
                 var1_bin_labels=None, aggregation_method='%frequency'):
    """
    Accepts 2 timeseries of different variables and computes the distribution of second variable 
    with respect to the bins of the first variable. If only one var1 is sent then it computes 
    the distribution of itself.

    :param var1_series: Series of the variable which we want to bin against and if var2_series is 
        not sent whose distribution we need to find.
    :param var2_series: Series of the variable whose distribution we need to find, if sent.
    :param var1_bin_array: Array of numbers where adjacent elements of array form a bin.
    :param var1_bin_labels: Labels of bins to be used, uses (bin-start, bin-end] format by default
    :param aggregation_method: Statistical method used to find distribution it can be mean, max,
        min, std, count, describe, a custom function, etc. Using '%frequency' computes frequency in
        percentages by default.
    :returns: A plot of the distribution and, if required, a DataFrame/Series with bins as row 
        indexes and columns with statistics chosen by aggregation_method.

    """
    return distribution_plot, distribution_data


def distribution_by_wind_speed(wind_speed, return_data=False)
    # should accept a freq_table or a timeseries.
    If time series:
        return distribution(wind_speed_series, var1_bin_array=np.arange(-0.5, 41, 1))
    If freq_table:
        return ...........
```

----------------

While I am looking at this. Does the below code mean that both series are now not concurrent or aligned anymore when NA are dropped in different places from both series? To bin one against the other don't you need to know that at this timestamp the temperature was this while the wind speed was this?
```python
    var1_series = var1_series.dropna()
    var2_series = var2_series.dropna()
```
If this is a bug then create a new issue.

**Comment by Inder95** [comment]
> An example of the basic `distribution` function with the `distribution_by_wind_speed` wrapping around it.
> 
> ```python
> # If plotting against itself then no need to send the same series twice as in distribution 
> # of wind speed.
> # Instead of var2_bin_array and var2_bin_labels can these be var1 to make the above work? 

I think this kills the idea of distribution function, where we can send any two variables like temperature with wind speed and get a distribution. As a user it would be confusing for me to see that var2 is optional. Also compromising the generality of this function for the special case of wind distribution might not be a good idea. We are not sending `wspd` twice in `distribution_by_wind_speed` but only inside it which does not bother me as a user.


> def distribution_by_wind_speed(wind_speed, return_data=False)
>     # should accept a freq_table or a timeseries.
>     If time series:
>         return distribution(wind_speed_series, var1_bin_array=np.arange(-0.5, 41, 1))
>     If freq_table:
>         return ...........
> ```

We can add a freq_table, just need an extra variable. But again we compromise simplicity as a user and I am thinking down the line if we change freq_table we will have a whole string of changes to make which will become intractable at some point.


> While I am looking at this. Does the below code mean that both series are now not concurrent or aligned anymore when NA are dropped in different places from both series? To bin one against the other don't you need to know that at this timestamp the temperature was this while the wind speed was this?
> 
> ```python
>     var1_series = var1_series.dropna()
>     var2_series = var2_series.dropna()
> ```
> 
> If this is a bug then create a new issue.

We drop the ones which are in one and not in the other in the line after this `data = pd.concat([var1_series.rename('data'), var2_binned_series], join='inner', axis=1)`. These two lines were needed because we do not NaN when we concat them again.

**Comment by stephenholleran** [comment]
> > While I am looking at this. Does the below code mean that both series are now not concurrent or aligned anymore when NA are dropped in different places from both series? To bin one against the other don't you need to know that at this timestamp the temperature was this while the wind speed was this?
> > ```python
> >     var1_series = var1_series.dropna()
> >     var2_series = var2_series.dropna()
> > ```
> > 
> > 
> > If this is a bug then create a new issue.
> 
> We drop the ones which are in one and not in the other in the line after this `data = pd.concat([var1_series.rename('data'), var2_binned_series], join='inner', axis=1)`. These two lines were needed because we do not NaN when we concat them again.

Ok, great. We work mostly in timeseries so should the doc string specify that the var1_series should be Time series as opposed to just a Series? If a Series is sent where the index is just a counter, what happens when a row is dropped with dropna()? If row with index 2 is dropped does row with index 3 then become 2 or does it stay at 3?

**Comment by stephenholleran** [comment]
> > An example of the basic `distribution` function with the `distribution_by_wind_speed` wrapping around it.
> > ```python
> > # If plotting against itself then no need to send the same series twice as in distribution 
> > # of wind speed.
> > # Instead of var2_bin_array and var2_bin_labels can these be var1 to make the above work? 
> > ```
> 
> I think this kills the idea of distribution function, where we can send any two variables like temperature with wind speed and get a distribution. As a user it would be confusing for me to see that var2 is optional. Also compromising the generality of this function for the special case of wind distribution might not be a good idea. We are not sending `wspd` twice in `distribution_by_wind_speed` but only inside it which does not bother me as a user.

What about when a user wants to get the distribution of temperature i.e. how often the temperature is above 20 deg C? This is common enough use case. The user needs to send temperature variable twice which is confusing to the user. It is not just for the special case of wind speed. This to me is a more common case for using distribution than for sending 2 variables. Using 1 variable is more like a histogram however as there are different aggregation methods it is only a histogram for counting the frequencies of occurrence.

When we want the frequency or mean of temperature for each wind speed bin the temperature can be the second variable that is binned against the first.

We can split this function up further into 1 or 2 variable options or I think make it user friendly when only dealing with 1 variable and have var2 as optional?

**Comment by stephenholleran** [comment]
@Inder95 I think you have introduced a bug with the 'overlaps' or something. The wind rose plot now doesn't plot correctly. 


This is what it should look like. See the values by direction summed match the outside of the wedge for each sector. Specifically the south west sectors with values 14.0 and 14.8.
![image](https://user-images.githubusercontent.com/25622575/58648422-8faa0100-8301-11e9-9ff2-3fe08789927e.png)



This is with your working branch. See the same south west sectors along with the north west is plotting to the 17 something even though the table numbers are the same.
![image](https://user-images.githubusercontent.com/25622575/58647887-676dd280-8300-11e9-88ba-004a2ec018a3.png)

**Comment by Inder95** [comment]
> @Inder95 I think you have introduced a bug with the 'overlaps' or something. The wind rose plot now doesn't plot correctly.
> 
> This is what it should look like. See the values by direction summed match the outside of the wedge for each sector. Specifically the south west sectors with values 14.0 and 14.8.
> ![image](https://user-images.githubusercontent.com/25622575/58648422-8faa0100-8301-11e9-9ff2-3fe08789927e.png)
> 
> This is with your working branch. See the same south west sectors along with the north west is plotting to the 17 something even though the table numbers are the same.
> ![image](https://user-images.githubusercontent.com/25622575/58647887-676dd280-8300-11e9-88ba-004a2ec018a3.png)

Will look into it. Is that campbell_scientific data?

**Comment by stephenholleran** [comment]
> Will look into it. Is that campbell_scientific data?

I'm afraid not. But it does the same for campbell scientific. This is master branch.
![image](https://user-images.githubusercontent.com/25622575/58662900-20dd9f80-8323-11e9-9420-8c5e8b0c23c0.png)

Working branch:
![image](https://user-images.githubusercontent.com/25622575/58662958-44084f00-8323-11e9-95ef-5876675bd81d.png)

**Comment by Inder95** [comment]
@stephenholleran I fixed the bug, it was summing the wrong rows for calculating the colors in rose.

![image](https://user-images.githubusercontent.com/23189856/58881006-25160e00-86d1-11e9-99f4-26f04c414e80.png)

Also as mentioned in https://github.com/brightwind-dev/brightwind/issues/46#issuecomment-496206399 I set the default values of `plot_bins` and `plot_labels` have to be explicitly specified as None if we do not want to use the default case of wind speeds:

```
    graph, tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 10, 15, 50],
                               var_bin_labels=['low', 'mid', 'high'], plot_bins=None, plot_labels=None,
                               return_data=True)

    tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 8, 14, 41], var_bin_labels=['low', 'mid', 'high'],
                        direction_bin_array=[0, 90, 130, 200, 360],
                        direction_bin_labels=['northerly', 'easterly', 'southerly', 'westerly'],
                        plot_bins=None, plot_labels=None, return_data=True)
```
This is not good. In my opinion, we should go back to the solution where I mentioned the particular case of wind speeds in the docstring and let the code choose appropriate bins. What do you say?

**Comment by Inder95** [comment]
@stephenholleran  Having var2 as optional was a good idea, implemented. Please proofread the docstring. And for plot_wind_rose in iss #52, we are now using it in distribution_by_dir and I think we don't need more wrappers around it. Let me know what you think.

**Comment by stephenholleran** [comment]
> Also as mentioned in [#46 (comment)](https://github.com/brightwind-dev/brightwind/issues/46#issuecomment-496206399) I set the default values of `plot_bins` and `plot_labels` to the specific case of wind speeds but have to be explicitly specified as None if we do not want to use that,
> 
> ```
>     graph, tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 10, 15, 50],
>                                var_bin_labels=['low', 'mid', 'high'], plot_bins=None, plot_labels=None,
>                                return_data=True)
> 
>     tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 8, 14, 41], var_bin_labels=['low', 'mid', 'high'],
>                         direction_bin_array=[0, 90, 130, 200, 360],
>                         direction_bin_labels=['northerly', 'easterly', 'southerly', 'westerly'],
>                         plot_bins=None, plot_labels=None, return_data=True)
> ```
> 
> This does not look good. In my opinion, we should go back to the solution where I mentioned the particular case of wind speeds in the docstring and let the **code** choose appropriate bins. What do you say?

Do you mean ' _....let the **coder** choose....._'?
If so then, no. We need to make it as easy as possible for the user.

**Comment by Inder95** [comment]
> > Also as mentioned in [#46 (comment)](https://github.com/brightwind-dev/brightwind/issues/46#issuecomment-496206399) I set the default values of `plot_bins` and `plot_labels` to the specific case of wind speeds but have to be explicitly specified as None if we do not want to use that,
> > ```
> >     graph, tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 10, 15, 50],
> >                                var_bin_labels=['low', 'mid', 'high'], plot_bins=None, plot_labels=None,
> >                                return_data=True)
> > 
> >     tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 8, 14, 41], var_bin_labels=['low', 'mid', 'high'],
> >                         direction_bin_array=[0, 90, 130, 200, 360],
> >                         direction_bin_labels=['northerly', 'easterly', 'southerly', 'westerly'],
> >                         plot_bins=None, plot_labels=None, return_data=True)
> > ```
> > 
> > 
> > This does not look good. In my opinion, we should go back to the solution where I mentioned the particular case of wind speeds in the docstring and let the **code** choose appropriate bins. What do you say?
> 
> Do you mean ' _....let the **coder** choose....._'?
> If so then, no. We need to make it as easy as possible for the user.

No, I have added a functionality where if no bins are send, the code automatically bins data into appropriate number of equally sized bins. The coder does not have to do anything, but only in the case when she wants to specify custom bins as in the case of wind-speed (example in the docstring).

**Comment by Inder95** [comment]
- [ ] distribution() func should plot the distribution like other functions. I have made the changes but the plot_freq_distribution() function can't handle when the bin_labels are a category.
 note for myself

**Comment by stephenholleran** [comment]
Items to resolve to close this out:

- [ ] plot_bins and plot_labels default values as below.

> > > ```
> > >     graph, tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 10, 15, 50],
> > >                                var_bin_labels=['low', 'mid', 'high'], plot_bins=None, plot_labels=None,
> > >                                return_data=True)
> > > 
> > >     tab = bw.freq_table(df.Spd40mN, df.Dir38mS, var_bin_array=[0, 8, 14, 41], var_bin_labels=['low', 'mid', 'high'],
> > >                         direction_bin_array=[0, 90, 130, 200, 360],
> > >                         direction_bin_labels=['northerly', 'easterly', 'southerly', 'westerly'],
> > >                         plot_bins=None, plot_labels=None, return_data=True)
> > > ```
> > > 
> > > 
> > > This does not look good. In my opinion, we should go back to the solution where I mentioned the particular case of wind speeds in the docstring and let the **code** choose appropriate bins. What do you say?
> > 
> > 
> > Do you mean ' _....let the **coder** choose....._'?
> > If so then, no. We need to make it as easy as possible for the user.
> 
> No, I have added a functionality where if no bins are send, the code automatically bins data into appropriate number of equally sized bins. The coder does not have to do anything, but only in the case when she wants to specify custom bins as in the case of wind-speed (example in the docstring).

**Comment by stephenholleran** [comment]
Items to resolve to close this out:

- [ ] TI.by_speed() bug due to plot_freq_distribution() changing

- [ ] TI.by_speed() new bug. See image below.

![image](https://user-images.githubusercontent.com/25622575/59513368-9fedde80-8eb2-11e9-82b9-0cf5b3df3ec8.png)

**Comment by Inder95** [comment]
@stephenholleran  All but the multiple plots issue have been resolved, feel free to merge this branch.
