### ISSUE TITLE
[average_data_by_period] improve usability of applying coverage_threshold.

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#48]
When I was using this I forgot to set the `filter_by_coverage_threshold=True` to apply the coverage_threshold.

If I set the coverage_threshold to something then it should be applied.

Improve usability by setting the default `coverage_threshold=None` then if it is set to a number  (between 0 and 1) you automatically apply the filter_by_coverage_threshold. If it is still None then you don't. This removes the need to set 2 parameters when applying the coverage_threshold and you can still set it to 1 if you want.

coverage_threshold could either be set to '0', instead of 'None', by default and the coverage_threshold is always applied. As it is '0' it acts as if coverage_threshold is not applied.

The doc string should be updated along with tests.

An error msg should be returned if a coverage_threshold value outside of 0 to 1 is sent to let the user know quickly what went wrong.

**Comment by stephenholleran** [comment]
I made some edits in the branch. Main thing is removing the need to set the filter true or false. Just apply it all the time and when coverage is 0 it doesn't filter anything.

Does this make the function run slower?

**Comment by Inder95** [comment]
Not much, because we are using vector operations for filtering (dataframe based) which are super fast. Also there were two other redundant/problematic lines, which I noticed. Pushed a commit correcting them. @stephenholleran Feel free to merge the branch into master.

**Comment by stephenholleran** [comment]
Merged
