### ISSUE TITLE
[Shear.by_sector]  warning msg about colours and indexing

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#54]
I get two warning messages when trying to run the Shear.by_sector function.

![image](https://user-images.githubusercontent.com/25622575/57445735-e49ab000-724a-11e9-925d-57ed82023692.png)

The 'c' argument is similar to iss #44. Maybe search all functions to change 'c' to 'colors'?

Not sure what the other warning msg is referring to. Link in the error msg:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-deprecate-loc-reindex-listlike

**Comment by Inder95** [comment]
Resolved this issue in the same branch as Shear because the code was moved to a separate file. @stephenholleran  you can close this issue if you are satisfied. We will merge this branch later into the master once we finish Shear.

**Comment by stephenholleran** [comment]
ok
