### ISSUE TITLE
[Shear] complete refactor

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#55]
Complete refactor of the Shear class.

Should Shear be in a separate file like correlation.py as it both analyses and transforms data which is outside the standard layout of the library similar to correlations?

Overall we want to be able to analyse (plot) the shear values and then use the results to transform the data based on an analyst's decision.

As an analyst I want to be able to:
- [x] calculate the power law, alpha, for individual wind speeds or a time series of wind speeds so I can do some ad hoc post processing.

- [x] see the shear profile with the power and log law profiles overlaid so I can check the relative wind speeds, review the profiles relative to each other and use the resulting alpha log law info in further processing.

- [x] see the shear by sector so I can decide if I want to shear up the wind speeds by direction sector and use the table from this to shear the data.

- [x] see the shear by time period i.e. by month for seasonal shear, by hour of day for diurnal shear, both together i.e. 12x24 of shear and use the resulting table to shear the data.

- [ ] apply the shear by a mixture of either by direction, by month and/or by hour of day using the power law alpha or the log law.

Applying the shear scaling factors should be applied to any wind speed an analyst wants either a single wind speed value (and height) or a time series of wind speeds.

**Comment by Inder95** [comment]
We can structure it similar to sector_ratio and TI, where we have a class Shear and various functions related to it in analyse. Only one function that does transform should sit in the transform sub-module but we the access to it will be from the class in analyse. I have added the existing code and the structure in that format in a new branch here.

**Comment by Inder95** [comment]
Hey @stephenholleran, I have made some changes to Shear.power_law based on the first point. Can you review the docstring, I think it needs more technical information of what power law, Shear, etc. is. Also can you tell me the alpha value of some data you know is correct to add to the tests.

**Comment by stephenholleran** [comment]
[7.74, 8.2, 8.57], [60, 80, 100]
alpha = 0.199474297

[8, 8.365116], [80, 100]
alpha = 0.2

**Comment by stephenholleran** [comment]
renamed the private function.
cleaned up a few things.

Why not use self as the first argument? Its highlighting loads of errors.

**Comment by Inder95** [comment]
> Why not use self as the first argument? Its highlighting loads of errors.

They way we decided to use Shear was similar to TI and sector_ratio. It is a collection of functions which help us do shear. We need self as the argument when we use Correlations, as we first create an object, train that object and then do things with that object. That might be a good option going forward for Shear but for now lets keep things simple by treating each function of Shear as independent of the other. For removing the pycharm warnings I have added `@staticmethod` decorators.

**Comment by Inder95** [comment]
> * [ ]  see the shear profile with the power and log law profiles overlaid so I can check the relative wind speeds, review the profiles relative to each other and use the resulting alpha log law info in further processing.

@stephenholleran Can you explain how log law is implemented?

**Comment by stephenholleran** [comment]
Issues:

- [ ] Average using 'log_law'

    - [ ] .alpha; change _aplha to alpha in AttributeError msg `'Average' object has no attribute 'alpha'`. Or don't have alpha. Applies to all Classes.

    - [ ] .info; `roughness_coef` of 36 is way too high. Is this roughness coef correct?

    - [ ] .apply; doesn't run, unexpected 'rough_coef'

- [ ] plot.py; could the shear profile extend up to 120m or if a meas level is higher to that?

- [ ] BySector using `log_law`

    - [ ] didn't plot when ran.

    - [ ] no .plot method.

    - [ ] .apply; `SettingWithCopyWarning` comes up. The warning msg recommends using `.loc[row_indexer,col_indexer] = value` instead. Why not?

- [ ] TimeOfDay using `log_law`

    - [ ] plots roughness values which are up on 36. Same issue as above. Not sure what to plot though??

    - [ ] .apply; FloatProgress doesn't work.

**Comment by lucunnin** [comment]
> Average using 'log_law'

> .alpha; change _aplha to alpha in AttributeError msg 'Average' object has no attribute 'alpha'. Or don't have alpha. Applies to all Classes.

Finding it difficult to solve this issue. At the moments, there is a trade-off between allowing the alpha value to be set by the user after calcualtion (which is undesirable) and the alpha attirbute being displayed for all instances of the method, i.e. the log_law instances. I have researched this and its appears that there is not an ideal solution for having a read only property in Python as this is considered unpythonic and so is not common.

>  BySector using log_law
> didn't plot when ran
There is currently no plot. What would be plotted in this case? The roughness coefficient?

>  .apply; SettingWithCopyWarning comes up. The warning msg recommends using .loc[row_indexer,col_indexer] = value instead. Why not?
This syntax does not work in this scenario. Using "pd.options.mode.chained_assignment = None" at the top of the shear.py solved this for me, I will try find an alternate solution

**Comment by stephenholleran** [comment]
**Average** using 'power_law'

- [ ] obj. - when i . hit tab on the return object it shows 'c'. What is 'c'? Could it be name differently or removed?

- [ ] .info - `shear_exponent(alpha)` I'm not sure the brackets is good to have in a name. Why not just `alpha`? If not, then just `shear_exponent`.

- [ ] plot - `np.linspace(0, max(heights), num=100)` instead of even spaces just use a numpy array in steps of 1. (PyCharm is throwing a warning on linespace too.) Also, start the array at 1 as the plot looks strange when it jumps to 0. `plot_heights = np.arange(1, max(heights)+1, 1)`

- [ ] .apply - name of return series is taken from the wspd sent to it. For safety, maybe rename this to the original + '_200' or whatever the 'height_to_scale_to' is?

- [ ] .apply - rename `height_to_scale_to` to  `shear_to`? I think anyone using shear understands that you need to shear up to a certain height.

- I see the .apply() can now take a list. Great.

- The `max_plot_height` is good and good that it is defaulted to None as LiDAR data can be any height.

**Comment by stephenholleran** [comment]
**BySector** using 'power_law'

- [ ] .apply() - still getting the warning. I updated Jupyter Notebook version to 5.7.8 and pandas to 0.24.2.

**Comment by stephenholleran** [comment]
**TimeOfDay** using 'power_law'

- [ ] rename`daily_segments` to `segments_per_day`?

- [ ] rename `day_start_time` to `segment_start_time`? Put `segments_per_day` before `segment_start_time` in the arguments order.

- [ ] error when `day_start_time` is a string is not great. The error is because it can't calculate with a string. `TypeError: not all arguments converted during string formatting`

- [ ] for errors put the argument name in single quotes => `raise ValueError("'day_start_time' must be an integer between 0 and 24")`

- [ ] `ValueError: 'daily_segments' must be a divisor of 24` add in `from the list 1, 2, 3, 4, 6, 8, 12, 24`. Note that `1` throws an error. With `1` this would give the average daily shear in a month. This might be useful??

- [ ] plot size is too small.

- [ ] .info - `'day_start_time': '6'` 6 is a string when it should be a number.

- [ ] .alpha - does the alpha value represent up to 6am or from 6am. Explain in the doc string.

**Comment by stephenholleran** [comment]
**TimeSeries** using 'power_law'

- [ ] Would a progress bar be good during calculation?

- [ ] add an argument called `maximise_data`. Default 'False' but when 'True' it will maximise the data by calculating a shear value for a timestamp that has at least 2 valid wind speed values.

- [ ] .apply() - returned series has no name.

- [ ] .info - `'concurrent_period_in_years': 1.309,` I would have expected a much higher value (+1.5 yrs) than this seen as we are calculating shear when only 2 wind speeds are available?

**Comment by stephenholleran** [comment]
Forgot this one:

- [ ] 12x24 plot with 12 months. The line colours start repeating themselves. Would green shaded colours or Inder has yellow to green be better?

**Comment by stephenholleran** [comment]
- [ ] Average can't take a list of wind speeds due to calculating the coverage.

- [ ] BySector change the wedge colour of the frequency to be lighter asphalt with asphalt border.

- [ ] change roughness_coefficient to roughness and make it not settable.

- [ ] TimeOfDay make it more intuitive that the time 8:00:00 is for the start time of the segment.

**Comment by stephenholleran** [comment]
- [ ] Make error for when the number of wind speeds doesn't match the number of heights sent more descriptive. This is what we get: `TypeError: expected x and y to have same length`. The 'x' and 'y' could be replaced with wspds and heights.

**Comment by stephenholleran** [comment]
- [ ] Update doc strings to be more reflective of the wspds datatypes that can be sent.

**Comment by stephenholleran** [comment]
- [ ] In doc string change 'alpha' to 'roughness' `average_log_law.alpha`

**Comment by stephenholleran** [comment]
- [ ] In doc strings add in 'rtype' for the return type.

**Comment by stephenholleran** [comment]
- [ ] in _scale delete `slope` and `intercept` as they are not used.

- [ ] In `_calc_log_law()` line 876; `wspds = wspds.drop(wspds[wspds == 0].index.values.astype(int))  # take log of speeds` I think this comment is for power_law?

- [ ] Also in `_calc_log_law()` would it make the code cleaner if this returns roughness only?

- [ ] Is `_calc_roughness_coeff()` used any more? If not then delete.

**Comment by stephenholleran** [comment]
- [ ] There are a lot of `Local variable xxxxx might be referenced before assignment` warnings in the code. Any work around?

- [ ] Try and minimise all the PyCharm warnings.

**Comment by stephenholleran** [comment]
I made some changes. Mostly to the doc strings but the odd bit of code.

When you `bw.Shear.` and tab all the other library packages come up. I thought you had a fix for that?

**Comment by lucunnin** [comment]
Hey,

Yeah I have found a fix, but it is going to be in a different branch as we
discussed?
