### ISSUE TITLE
[plot_timeseries] enhancements around dates

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#56]
A few issues regarding the 'date_from' and 'date_to' usability.

- [x] Raise an error msg if date_from is greater than date_to.

- [x] If only date_from is supplied then plot from this date all the way to the end of the data. At present is doesn't splice and plots the whole dataset.

- [x] If only date_to is supplied plot from the start of the dataset to the date_to.

This is more likely the `utils._slice_data()` which needs the refactoring.

Also:
- [x] Update doc string with example usage.

**Comment by stephenholleran** [comment]
The `date_to` and `date_from` should be in yyyy-mm-dd format in the doc string and should be encouraged everywhere in the library. The `pandas.to_datetime()` function doesn't capture a 01-02-2019 (1st Feb) correctly as it is by default set to American date format of mm-dd-yyyy and so will think it is 2nd Jan. See iss #28 about this.

Don't use examples of mm-dd-yyyy.

**Comment by Inder95** [comment]
I was of the opinion that not specifying the format would make it easier for users as they can then send datetime objects too, or other formats. But I changed as we had previously decided.

**Comment by stephenholleran** [comment]
Great.
