### ISSUE TITLE
[export_tab_file] update header info

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#65]
Put info into the header of the tab file such as
- timestamp of creation,
- mean wind speed of the tab file
- version of the library that created it

**Comment by Inder95** [comment]
> Put info into the header of the tab file such as
> 
> * timestamp of creation,
> * mean wind speed of the tab file
> * version of the library that created it

Where to add in the header? I based this function on the infor given here: http://www.cancalia.com/wp-content/uploads/2015/10/How_to_create_and_formatMetTABfiles.pdf

**Comment by stephenholleran** [comment]
The header is the first line. We can write what we want in it. Don't worry about this. I'll do it.
