### ISSUE TITLE
How do we put a tutorial into the documentation web site?

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#76]
I have a tutorial for getting started which starts with downloading Anaconda for Windows and then cloning the library and getting it working in Jupyter Notebooks. It is currently in word with screen shots throughout. What format should it be put in and where should it be placed?

**Comment by Inder95** [comment]
The tutorials could be notebooks themselves. From a notebook we can export the code as markdown and all our webpages are created from markdown files. So just send me the notebook, or share the word document here and I will put in a notebook. 

Once you are done creating a notebook, put it in the docs folder in the same location as Tutorials.rst. This file contains a list of tutorials. Make sure that the name in the list matched your filename. Sphinx automatically detects that tutorial and creates a webpage.

**Comment by Inder95** [comment]
@stephenholleran  @lucunnin If you are uploading any tutorial in the docs just let me know. It will be easy to show by an example how a tutorial is included.

**Comment by lucunnin** [comment]
@Inder95 
I will make a branch with the tutorial markdown files I have created in it so you can access them

**Comment by Inder95** [comment]
@lucunnin 
- I have added a folder named tutorials in docs which will have the tutorial files.
- Upload the notebooks themselves instead of markdown, Sphinx automatically handles conversions and it will be better to have easily editable notebook in the repo itself.
- There is an error in Getting_Started_Stable_Development where SectorRatio is used instead of the new name given to this function. (Another reason we need notebooks in the repo, it is easy to debug)
- Also could you explain the convention Stable/Unstable and which one to use.

**Comment by lucunnin** [comment]
@Inder95 
Sure, I will upload those notebooks ASAP.

The idea the Stable/Unstable is that the Stable development will be for users who simply want to use the library, i.e. install using PyPy , and the Unstable development will be for those who wish to clone to git repositiory for the latest updates to the library and possible contribute.

**Comment by Inder95** [comment]
@lucunnin The images are not visible in the tutorial. Could you please look into other ways of including them or upload those images in the tutorials folder in the repo itself.

**Comment by lucunnin** [comment]
@Inder95 

I will upload the images themselves. I will name them in order of occurence in each notebook, i.e. Getting_Started_1, Getting_Started_2 so you know where to put each one.

**Comment by Inder95** [comment]
Few points to note when adding images to tutorials:

- Add images in the tutorials directory
- When referencing images from the notebook use
```
<center>

![image1](Stable_Getting_Started_1.png)

</center>

```
Instead of something like:
```
![](Stable_Getting_Started_1.png)
```
- Things in notebooks might appear a bit different from their html versions. So go through the notebooks once you are finished adding it to the documentation.

**Comment by stephenholleran** [comment]
> * Add images in the tutorials directory
> * When referencing images from the notebook use
> 
> ```
> <center>
> 
> ![image1](Stable_Getting_Started_1.png)
> 
> </center>
> ```

To add to that. Sphinx ignores <br> to insert a newline therefore images are too close. Use the div tag as a wrap around which has margin spacing inserted directly into the tag.

```
<div style='margin-top: 3em; margin-bottom: 3em;'>
<center>
![image1](images/getting_beta_versions_1.png)
</center>
</div>
```

**Comment by stephenholleran** [comment]
I have created a `template_tutorial.ipynb` which can be copied to get started with a new tutorial. It can be found in `....\brightwind\docs\source\tutorials` (once it is merged).

**Comment by stephenholleran** [comment]
- [ ] update Jupyter Notebook tutorial template

**Comment by stephenholleran** [comment]
**How to create a tutorial**

1. Copy the 'template_tutorial.ipynb' located in `..\brightwind\docs\source\tutorials` and rename it to your tutorial name.

1. Write your tutorial following the instructions in the 'template_tutorial' placing any images used into the 'image' sub-folder.

1. Update the 'tutorial_welcome.ipynb' with the new link to the tutorial.

1. To check how your new tutorial will look you need to run sphinx-docs to create the website locally. You do this by (this is also explained in the '**brightwind-docs**' readme):
    1. git clone the '**brightwind-docs**' repo next to your '**brightwind**' repo i.e. both '**brightwind**' and '**brightwind-docs**' are in the same folder.
    1. Then, navigate to the 'docs' folder in the '**brightwind**' repo where there should be a 'makefile'. From
here you can download the sphinx-bootstrap-theme using the following command: `C:\..\brightwind-dev\brightwind\docs> pip install sphinx-bootstrap-theme`

    1. Also install: 
    `C:\..\brightwind-dev\brightwind\docs> pip install nbsphinx --user`
    `C:\..\brightwind-dev\brightwind\docs> pip install m2r`

    1. If a module file has not yet been created this will need to be done e.g.
    `C:\..\brightwind-dev\brightwind\docs> sphinx-autogen -o  generated source\API.rst`

    1. If already set up then simply run
    `C:\..\brightwind-dev\brightwind\docs> make html`

    1. To view the new website locally go back to the '**brightwind-docs**' repo you cloned and `git checkout gh-pages`. The website files are contained in this branch. Double click the 'index.html' and this will open up the new website in a local browser. Navigate to your new tutorial and make sure the style formatting is reasonable. It will not match what was in the notebook but should be close.

1. If all OK, go back to your '**brightwind**' repo and git commit and push those changes to a new branch and request a pull request.
