### ISSUE TITLE
[ReadMe] update section on producing the documentation

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#79]
- [x]  `pip install m2r` is required

- [x] Once `make html` is run how does the documentation get to the 'gh-pages' branch in the 'brightwind-doc's repo?

**Comment by Inder95** [comment]
The source directory in the makefile points to folder containing docs gh-pages branch. The brightwind-docs should be in the same folder as brightwind

**Comment by stephenholleran** [comment]
> The source directory in the makefile points to folder containing docs gh-pages branch. The brightwind-docs should be in the same folder as brightwind

I'm afraid I do not follow! Can you elaborate?

1. Do I have to clone the 'brightwind-docs' repo first? Along with the 'gh-pages' branch?

1. Once `make html` is run I then simple push the gh-pages branch?

1. Do I need to be in the 'gh-pages' branch?

**Comment by Inder95** [comment]
> > The source directory in the makefile points to folder containing docs gh-pages branch. The brightwind-docs should be in the same folder as brightwind
> 
> I'm afraid I do not follow! Can you elaborate?
> 
> 1. Do I have to clone the 'brightwind-docs' repo first? Along with the 'gh-pages' branch?

Yes you need to clone the `brightwind-docs` repo. It should be in the same folder as your `brightwind` repo.

> 2. Once `make html` is run I then simple push the gh-pages branch?

Short answer, yes. If you open the makefile you will see that the destination folder is set to `brightwind-docs` so the html files that are created will automatically be in the gh-pages branch.
 
> 3. Do I need to be in the 'gh-pages' branch?

You need to be in the branch to push it and see the changes locally first. Pycharm gives you options to check html files in browser. So yes, but I don't think its very necessary but you will almost always be in that branch.

**Comment by stephenholleran** [comment]
OK, great. I follow that.

We created a new function called `export_csv()` in export.py. How do we get that added to the API documentation page?

**Comment by Inder95** [comment]
> OK, great. I follow that.
> 
> We created a new function called `export_csv()` in export.py. How do we get that added to the API documentation page?

Add the function in the file called API.rst, have a look at the file and you will see how to add it. Right now we need to manually add the function name to that list but I am trying to automate that too.


> We also made changes to the `export_tab_file()` function but the changes are not showing up in the doc string? Apart from indentation errors it ran ok.

Strange, check whether all the html files are added to git, some of them will be in different colors showing they were ignored during the push.

**Comment by stephenholleran** [comment]
> > We also made changes to the `export_tab_file()` function but the changes are not showing up in the doc string? Apart from indentation errors it ran ok.
> 
> Strange, check whether all the html files are added to git, some of them will be in different colors showing they were ignored during the push.
> Did you check in pycharm if it was showing the changes?

I haven't pushed it. Just looking at it on my local machine. Viewing it in PyCharm shows the same as opening up the index.html directly.

**Comment by Inder95** [comment]
> > > We also made changes to the `export_tab_file()` function but the changes are not showing up in the doc string? Apart from indentation errors it ran ok.
> > 
> > 
> > Strange, check whether all the html files are added to git, some of them will be in different colors showing they were ignored during the push.
> > Did you check in pycharm if it was showing the changes?
> 
> I haven't pushed it. Just looking at it on my local machine. Viewing it in PyCharm shows the same as opening up the index.html directly.

Not sure then, will have a look at it once dist() is sorted. Meanwhile check if there is indentation error in the export_tab_file()
