### ISSUE TITLE
freq_table labels have % symbol even though count requested

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#8]
`bw.freq_table(df.Spd_80m, df.Dir_80m, freq_as_percentage=False)`

![image](https://user-images.githubusercontent.com/25622575/48660578-cd2cf800-ea5b-11e8-9c63-a7944187452d.png)

**Comment by stephenholleran** [comment]
Hi Inder, can you leave a little comment about what you did or at least a link to the commit.

**Comment by Inder95** [comment]
The link is right here:
![image](https://user-images.githubusercontent.com/23189856/51108148-0ded8700-17e9-11e9-8c13-b32c9e4690c2.png)

**Comment by stephenholleran** [comment]
I'm learning!
