### ISSUE TITLE
[Tutorial] to show how to scale a wind speed 

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#85]
- [x] Demonstrate simply scaling a time series wind speed in a DataFrame and how you can apply this to another column in the same DataFrame.
- [ ] Demonstrate with the use case of scaling a wind speed before it feeds into freq_table().

**Comment by ShaneBrightWind** [comment]
Andy can you add the following functions to this tutorial.

average_data_by_period
adjust_slope_offset
offset_wind_direction
offset_timestamps

**Comment by ShaneBrightWind** [comment]
Can you also call this file the following:

how_to_transform_your_data

**Comment by ShaneBrightWind** [comment]
Add in selective averaging function to this also
