### ISSUE TITLE
[Tutorial] to explain how distribution() works

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#86]
- [ ] First show how distribution_by_wind_speed() is a wrapper around distribution()

- [ ] Show how distribution() works with 1 variable with default parameters and explain what the plot is showing along with the data table returned.

- [ ] Show how distribution works with 1 variable but with different bins.

- [ ] Show how distribution() works with 2 variables and explain what the plot is showing.

- [ ] Show how to use a custom aggregation function and how to create one.

**Comment by ShaneBrightWind** [comment]
Found issue with Distribution() function. It always shows 'Speed m/s' on the x-axis, even if other variables are plotted. This should be modified to allow other x-axis variables to be inputted.
