### ISSUE TITLE
[SectorRatio].[by_sector] break this out from a class

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#88]
This function is currently in a class. There isn't many other functions that could be included in this class so I suggest taking it out from a class. Therefore it can be used like most other functions.

e.g.
```python
bw.wspd_ratio_by_dir(data.Spd80mN, data.Spd80mS..........)
```

**Comment by stephenholleran** [comment]
- [ ] Can we have the minimum wind speed limit as an input variable instead of hard coded in the calc() function. Could be called min_wspd=3 with a default of 3m/s.

**Comment by lucunnin** [comment]
Yes, I have made this changes and updated the pull request.
