### ISSUE TITLE
[distribution_matrix] new distribution func to show distribution against 2 variables

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#93]
This follows on from previous discussions in iss #46 which got too large to follow.

This is a new function to find the distribution of a variable against two others. Similar to the freq_table() however that is a specific use case involving wind direction.

Use case for this new function:
As an analyst I want a plot/table to show how often a certain TI value occurs (%frequency) within certain TI and wind speed bins so I can get an idea on how the turbine will perform.

Similar to this table from RES:
![image](https://user-images.githubusercontent.com/25622575/59511092-4f27b700-8ead-11e9-9c33-08f6b2343f66.png)

Or these:
![image](https://user-images.githubusercontent.com/25622575/59511351-f0167200-8ead-11e9-8720-77936c1b651d.png)

**Comment by stephenholleran** [comment]
Plots looks good when you put a lot more bins than just 6.

1. Why is `var_to_bin_1` and `var_to_bin_2` set to None? That means that they are not needed but they are?

1. I'm struggling to use it:
    1. Can't seem to send Spd80mN twice, one to bin against and the other to count the %frequency?

1. The below doesn't work for some reason?

```python
ti = bw.TI.calc(data.Spd80mN, data.Spd80mNStd)
ti = ti*100
ti
plot, tab = bw.dist_matrix(data.T2m, var_to_bin_1=ti, var_to_bin_2=data.Spd80mN, return_data=True)
plot
```
Something to do with the `ti` but it is a pd.Series with a timestamp?


These are just a few quick ones.

**Comment by Inder95** [comment]
> Plots looks good when you put a lot more bins than just 6.
> 
> 1. Why is `var_to_bin_1` and `var_to_bin_2` set to None? That means that they are not needed but they are?

Changed

> 2. I'm struggling to use it:
>    
>    1. Can't seem to send Spd80mN twice, one to bin against and the other to count the %frequency?

Fixed

> 3. The below doesn't work for some reason?
> 
> ```python
> ti = bw.TI.calc(data.Spd80mN, data.Spd80mNStd)
> ti = ti*100
> ti
> plot, tab = bw.dist_matrix(data.T2m, var_to_bin_1=ti, var_to_bin_2=data.Spd80mN, return_data=True)
> plot
> ```
> 
> Something to do with the `ti` but it is a pd.Series with a timestamp?

ti Series didn't have a ti.name attribute, which the function used. I have fixed that and with that the ability to pass custom labels for all the 3 axes.

**Comment by stephenholleran** [comment]
Hi @Inder95 

Some more comments:

1. Would the names be better to reference the x and y axis they will be on i.e. 'var_to_bin_1' to 'x_series' and 'var_to_bin_2' to 'y_series'? This would match up with x_label, y_label.

1. Move the order of var_label, x_label and y_label up before aggregation_method.

1. The 'num_of_bins' argument originates comes from the freq_table as it has sectors. The number of bins is usually a number that divides nicely into 360. When we use that here the bin limits are 3 decimal places making it look poor. For dist() I take the max and min values in the series, round to an integer and then create an array in steps of 1. Can you remove the 'num_of_bins', rename 'bins_var_1' to 'x_bins' and set it to None?

```python
 if bins is None:
    bins = np.arange(round(var_to_bin_against.min()-0.5)-0.5, var_to_bin_against.max()+0.5, 1)
```

![image](https://user-images.githubusercontent.com/25622575/60190388-7aee5980-982a-11e9-9169-98eed7197da9.png)
`bw.dist_matrix(data.T2m, data.Spd80mN, data.T2m, num_bins_1=30, num_bins_2=30)`

This image looks good but some questions. Image is supposed to be the % of occurrence of a certain temp at a certain wind speed.

1. The numbers on the x and y axis don't make sense. It suggests that wind speeds are between -5.594 and 0.823? And T2m is between 1.174 and 6.932? Neither of these look right?

1. The color map label isn't quite right. Not sure why '_distribution' is in the label? In plot_12x24 we have used:
```python
cbar.ax.set_ylabel(label[1].capitalize() + " of " + label[0])
```
Where label[1] is 'mean' for example and label[0] is T2m.

Also, when var_label='Mean of T2m [deg C]' it comes out as 'mean Mean of T2m [deg C]'. Need to drop the first 'mean'

**Comment by Inder95** [comment]
> Hi @Inder95
> 
> Some more comments:
> 
> 1. Would the names be better to reference the x and y axis they will be on i.e. 'var_to_bin_1' to 'x_series' and 'var_to_bin_2' to 'y_series'? This would match up with x_label, y_label.

Done that,  good idea

> 2. Move the order of var_label, x_label and y_label up before aggregation_method.

Done

> 3. The 'num_of_bins' argument originates comes from the freq_table as it has sectors. The number of bins is usually a number that divides nicely into 360. When we use that here the bin limits are 3 decimal places making it look poor. For dist() I take the max and min values in the series, round to an integer and then create an array in steps of 1. Can you remove the 'num_of_bins', rename 'bins_var_1' to 'x_bins' and set it to None?
> 
> ```python
>  if bins is None:
>     bins = np.arange(round(var_to_bin_against.min()-0.5)-0.5, var_to_bin_against.max()+0.5, 1)
> ```

I don't think it is a good idea, as bins of width 1 are good only for a few cases like wind speed. But for many other variables the width of 1 will be too small or too big. Our current method takes that into account. But I have changed the names to x_bins and y_bins as you suggested.

> ![image](https://user-images.githubusercontent.com/25622575/60190388-7aee5980-982a-11e9-9169-98eed7197da9.png)
> `bw.dist_matrix(data.T2m, data.Spd80mN, data.T2m, num_bins_1=30, num_bins_2=30)`
> 
> This image looks good but some questions. Image is supposed to be the % of occurrence of a certain temp at a certain wind speed.
> 
> 1. The numbers on the x and y axis don't make sense. It suggests that wind speeds are between -5.594 and 0.823? And T2m is between 1.174 and 6.932? Neither of these look right?

Solved, was a difficult problem. Matplotlib ignores some ticks in between but does not ignore the tick labels.

> 2. The color map label isn't quite right. Not sure why '_distribution' is in the label? In plot_12x24 we have used:

_distributed was added to differentiate between aggregated columns and the original when same variabe was passed. But have changed this, you won't see it now.
![image](https://user-images.githubusercontent.com/23189856/61183787-6937ef00-a63d-11e9-9800-86658449d3cf.png)

> 
> ```python
> cbar.ax.set_ylabel(label[1].capitalize() + " of " + label[0])
> ```
> 
> Where label[1] is 'mean' for example and label[0] is T2m.
> Also, when var_label='Mean of T2m [deg C]' it comes out as 'mean Mean of T2m [deg C]'. Need to drop the first 'mean'


Fixed it.
![image](https://user-images.githubusercontent.com/23189856/61183809-9ab0ba80-a63d-11e9-9efd-ef7e0c2b5036.png)

**Comment by stephenholleran** [comment]
>> The 'num_of_bins' argument originates comes from the freq_table as it has sectors. The number of bins is usually a number that divides nicely into 360. When we use that here the bin limits are 3 decimal places making it look poor. For dist() I take the max and min values in the series, round to an integer and then create an array in steps of 1. Can you remove the 'num_of_bins', rename 'bins_var_1' to 'x_bins' and set it to None?

> I don't think it is a good idea, as bins of width 1 are good only for a few cases like wind speed. But for many other variables the width of 1 will be too small or too big. Our current method takes that into account. Fixing width would make the function less flexible for the user. And the one we have right now can be used for the case where bin widths are 1, as the user can specify x_bins which overwrites num_bin_x. But I have changed the names to x_bins and y_bins as you suggested.

The plots above that you created are difficult to read. It is difficult to pick out the numbers as there are 3 decimal places which then makes it difficult to see how big each step or bin is. I am not saying to 'fix' the steps to 1. I want to make it easy for the user so we will assume steps of 1 but the user can easily set the number of bins to whatever they want. The plots above would look a lot better and it doesn't take away any of the flexibility from the user.
```python

    if num_bins_x is None and x_bins is None:
        x_bins = np.arange(int(np.floor(x_series.min())), int(np.ceil(x_series.max()) + 1 + (x_series.max() % 1 == 0)), 1)
    elif num_bins_x is not None and x_bins is None:
        x_bins = np.linspace(x_series.min(), x_series.max(), num_bins_x + 1)
    elif x_bins is not None:
        x_bins = x_bins

    if num_bins_y is None and y_bins is None:
        y_bins = np.arange(int(np.floor(y_series.min())), int(np.ceil(y_series.max()) + 1 + (y_series.max() % 1 == 0)), 1)
    elif num_bins_y is not None and y_bins is None:
        y_bins = np.linspace(y_series.min(), y_series.max(), num_bins_y + 1)
    elif y_bins is not None:
        y_bins = y_bins

```
(Check my logic here!)

If you make the changes, see how easy it is to get something reasonable out on the first attempt.
![image](https://user-images.githubusercontent.com/25622575/61229369-f2275700-a71f-11e9-9d31-073880852633.png)

**Comment by stephenholleran** [comment]
Also;

1. Can you put 'x' first? Keeps consistent with the other x and y items and is more in line with how people think about x first and then y. 
    ```python
    def dist_matrix(var_series, y_series, x_series,......)
    ```

1. Capitalize the color bar label.
`aggregation_method.capitalize() `

**Comment by Inder95** [comment]
@stephenholleran Implemented your suggestions. Makes sense when you set num_bins default to None. Feel free to merge into master.
