### ISSUE TITLE
[TI.by_speed] bug plotting extra plots

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#98]
- [ ] TI.by_speed() new bug plotting extra plots. See image below.

![image](https://user-images.githubusercontent.com/25622575/59513368-9fedde80-8eb2-11e9-82b9-0cf5b3df3ec8.png)

_Originally posted by @stephenholleran in https://github.com/brightwind-dev/brightwind/issues/46#issuecomment-502114454_

**Comment by stephenholleran** [comment]
This doesn't seem to be a problem anymore?

**Comment by Inder95** [comment]
> This doesn't seem to be a problem anymore?

Yeah @lucunnin added those plt.close() I think, they seem to work well.
